const fs = require('fs');

const materials = JSON.parse(fs.readFileSync('all_drive_materials.json', 'utf8'));

// Map categories to official ENEM subject names or areas
function mapToSubject(cat) {
  const norm = cat.trim();
  if (norm === 'Língua Portuguesa') return 'Língua Portuguesa';
  if (norm === 'Literatura') return 'Literatura';
  if (norm === 'Artes') return 'Artes';
  if (norm === 'Educação Física') return 'Educação Física';
  if (norm === 'Inglês') return 'Inglês';
  if (norm === 'Espanhol') return 'Espanhol';
  if (norm === 'História') return 'História';
  if (norm === 'Geografia') return 'Geografia';
  if (norm === 'Filosofia') return 'Filosofia';
  if (norm === 'Sociologia') return 'Sociologia';
  if (norm === 'Biologia') return 'Biologia';
  if (norm === 'Física') return 'Física';
  if (norm === 'Química') return 'Química';
  if (norm === 'Matemática') return 'Matemática';
  if (norm === 'Redação') return 'Redação';
  return norm; // Atualidades, Guia do Estudo Perfeito - GEP, Provas Anteriores
}

const enriched = materials.map(m => {
  return {
    ...m,
    subjectName: mapToSubject(m.category)
  };
});

const tsCode = `// Autogenerated from user's Google Drive folder (ID: 1Hod97yNll2w-RpUYvfYqRRaMKjjZ5JVE)
// Total indexed: ${enriched.length} items

export interface DriveMaterial {
  id: string;
  title: string;
  fileName: string;
  category: string;
  subjectName: string;
  subfolder: string | null;
  mimeType: string;
  size: string | null;
  googleDriveId: string;
  driveUrl: string;
  embedUrl: string;
  downloadUrl: string;
  type: 'PDF' | 'AUDIO' | 'IMAGEM' | 'DOCUMENTO';
}

export const DRIVE_MATERIALS: DriveMaterial[] = ${JSON.stringify(enriched, null, 2)};

export const DRIVE_CATEGORIES = Array.from(new Set(DRIVE_MATERIALS.map(m => m.category))).sort();

export function getDriveMaterialsByCategory(category: string): DriveMaterial[] {
  if (!category || category === 'TODAS') return DRIVE_MATERIALS;
  return DRIVE_MATERIALS.filter(m => m.category.toLowerCase() === category.toLowerCase() || m.subjectName.toLowerCase() === category.toLowerCase());
}

export function getDriveMaterialsBySubject(subjectName: string): DriveMaterial[] {
  const norm = subjectName.toLowerCase();
  return DRIVE_MATERIALS.filter(m => 
    m.subjectName.toLowerCase().includes(norm) || 
    m.category.toLowerCase().includes(norm) ||
    (m.subfolder && m.subfolder.toLowerCase().includes(norm))
  );
}

export function searchDriveMaterials(query: string): DriveMaterial[] {
  if (!query) return DRIVE_MATERIALS;
  const q = query.toLowerCase().trim();
  return DRIVE_MATERIALS.filter(m =>
    m.title.toLowerCase().includes(q) ||
    m.fileName.toLowerCase().includes(q) ||
    m.category.toLowerCase().includes(q) ||
    (m.subfolder && m.subfolder.toLowerCase().includes(q))
  );
}
`;

fs.writeFileSync('src/db/driveMaterialsData.ts', tsCode, 'utf8');
console.log('Created src/db/driveMaterialsData.ts successfully!');

