import { SubjectData, TopicData, Disciplina, AreaDoConhecimento, OnlineStudyResource } from '../types';

// Curadoria dinâmica de materiais de alta qualidade na internet para o ENEM 2026
function getCuratedOnlineResources(discipline: Disciplina, topicName: string): OnlineStudyResource[] {
  const ytQuery = encodeURIComponent(`${topicName} ${discipline} enem aula completa`);
  const artigoQuery = encodeURIComponent(`${topicName} ${discipline} resumo enem brasil escola`);

  let provider = 'Canal Educação & Brasil Escola';
  if (discipline === 'Matemática' || discipline === 'Física') provider = 'Professor Ferretto / Khan Academy';
  else if (discipline === 'Biologia') provider = 'Biologia Total (Prof. Jubilut)';
  else if (discipline === 'Química') provider = 'Química em Ação (Prof. Michel)';
  else if (discipline === 'História' || discipline === 'Geografia') provider = 'Parabólica (Prof. Pedro Reno) / Nostalgia';
  else if (discipline === 'Filosofia' || discipline === 'Sociologia') provider = 'Brasil Escola / Filosofia Total';
  else if (discipline === 'Língua Portuguesa' || discipline === 'Literatura') provider = 'Português com Letícia / Toda Matéria';
  else if (discipline === 'Redação') provider = 'Redação e Gramática Zica';

  return [
    {
      id: `res-yt-${topicName.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      title: `Videoaula Completa: ${topicName} para o ENEM`,
      type: 'VIDEO',
      provider,
      url: `https://www.youtube.com/results?search_query=${ytQuery}`,
      description: `Aula aprofundada alinhada à matriz do INEP, com resolução de questões clássicas, análise de gráficos e macetes pedagógicos.`,
      durationOrReadingTime: '24 min',
    },
    {
      id: `res-art-${topicName.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      title: `Guia Didático & Resumo Fichado: ${topicName}`,
      type: 'ARTIGO',
      provider: 'Brasil Escola / Toda Matéria',
      url: `https://brasilescola.uol.com.br/busca?q=${artigoQuery}`,
      description: `Texto explicativo estruturado com conceitos essenciais, contextualização cotidiana e quadros conceituais.`,
      durationOrReadingTime: '10 min leitura',
    },
    {
      id: `res-mm-${topicName.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      title: `Mapa Mental & Esquema Síntese: ${topicName}`,
      type: 'MAPA_MENTAL',
      provider: 'MEC / Banco Aberto de Recursos Educacionais',
      url: `https://www.google.com/search?tbm=isch&q=${encodeURIComponent('mapa mental ' + topicName + ' enem ' + discipline)}`,
      description: `Esquematização visual com palavras-chave, conectores e desdobramentos temáticos para memorização rápida.`,
      durationOrReadingTime: 'Síntese visual',
    },
    {
      id: `res-inep-${topicName.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      title: `Exercícios Resolvidos e Comentados: ${topicName}`,
      type: 'RESUMO',
      provider: 'INEP / Portal do Estudante',
      url: `https://www.google.com/search?q=${encodeURIComponent('exercicios resolvidos ' + topicName + ' enem')}`,
      description: `Questões da prova oficial comentadas passo a passo com identificação de competências e distratores.`,
      durationOrReadingTime: '15 min prática',
    },
  ];
}

// Função auxiliar para gerar conteúdos didáticos enriquecidos para cada tópico
function createTopic(
  id: string,
  name: string,
  discipline: Disciplina,
  area: AreaDoConhecimento,
  theoryText: string,
  summaryBullets: string[],
  mindMapPoints: string[],
  flashcardsList: { front: string; back: string }[] = [],
  solvedExercisesList: { title: string; statement: string; resolution: string; steps: string[] }[] = [],
  customOnlineResources?: OnlineStudyResource[]
): TopicData {
  // Flashcards com garantia de cobertura ativa
  const finalFlashcards = [...flashcardsList];
  if (finalFlashcards.length === 0) {
    finalFlashcards.push(
      {
        front: `Qual é a essência cobrada em "${name}" (${discipline}) no ENEM?`,
        back: `${theoryText.slice(0, 170)}... O exame foca na aplicação desse conceito em situações práticas da sociedade e da natureza.`,
      },
      {
        front: `Quais são as palavras-chave prioritárias de "${name}"?`,
        back: `Conceitos centrais: ${mindMapPoints.slice(0, 4).join(', ') || name}. Atenção a relações de causa e efeito e leitura de dados.`,
      },
      {
        front: `Qual estratégia garante alta pontuação ao resolver questões de "${name}"?`,
        back: summaryBullets[0] || `Identificar a habilidade cobrada e descartar distratores que trazem afirmações verdadeiras mas alheias ao comando da questão.`,
      }
    );
  } else if (finalFlashcards.length === 1) {
    finalFlashcards.push({
      front: `Como "${name}" se relaciona interdisciplinarmente na prova do ENEM?`,
      back: `O ENEM conecta ${name} com sustentabilidade ambiental, cidadania, impactos tecnológicos e saúde pública.`,
    });
  }

  // Exercícios resolvidos com passo a passo garantido
  const finalExercises = [...solvedExercisesList];
  if (finalExercises.length === 0) {
    finalExercises.push({
      title: `Resolução Comentada Modelo ENEM: ${name}`,
      statement: `(ENEM 2026 - Questão Aplicada) Em uma análise prática relacionada a ${name.toLowerCase()} no contexto de ${discipline}, um estudante precisa avaliar como alterações em variáveis do sistema afetam o resultado final. Com base nos princípios teóricos e na matriz de competências do exame, a alternativa correta é aquela que:`,
      resolution: `Para resolver com precisão, o estudante deve: 1) Isolar os dados fornecidos no texto-base; 2) Aplicar a teoria fundamental de ${name}; 3) Confrontar cada assertiva eliminando aquelas que apresentam conclusões infundadas ou extrapolam o texto.`,
      steps: [
        '1. Leitura atenta do comando final para compreender o que se pede exatamente.',
        `2. Evocação dos conceitos fundamentais de ${name} (${discipline}).`,
        '3. Análise crítica das 5 alternativas para identificação de distratores conceituais.',
        '4. Seleção da alternativa que demonstra a aplicação mais sólida e coerente com a matriz do INEP.',
      ],
    });
  }

  const onlineResources = customOnlineResources || getCuratedOnlineResources(discipline, name);

  return {
    id,
    name,
    discipline,
    area,
    status: 'NAO_INICIADO',
    masteryPercentage: 0,
    theory: theoryText,
    summary: summaryBullets.length > 0 ? summaryBullets : [
      `Conceito fundamental e contextualização de ${name}.`,
      `Aplicações interdisciplinares mais recorrentes no exame.`,
      `Estratégia de resolução de questões e pontos de atenção.`,
    ],
    mindMapPoints: mindMapPoints.length > 0 ? mindMapPoints : [
      `Conceito Nuclear de ${name}`,
      'Aplicações no Cotidiano',
      'Relações Interdisciplinares',
      'Padrões Recorrentes no ENEM',
    ],
    flashcards: finalFlashcards.map((f, i) => ({
      id: `${id}-fc-${i + 1}`,
      front: f.front,
      back: f.back,
      topic: name,
      difficulty: i % 3 === 0 ? 'FACIL' : i % 3 === 1 ? 'MEDIO' : 'DIFICIL',
      mastered: false,
    })),
    solvedExercises: finalExercises.map((e, i) => ({
      id: `${id}-ex-${i + 1}`,
      title: e.title,
      statement: e.statement,
      resolution: e.resolution,
      steps: e.steps,
      difficulty: 'MEDIO',
    })),
    onlineResources,
    questionCount: Math.floor(Math.random() * 25) + 20,
  };
}

export const ENEM_CURRICULUM: SubjectData[] = [
  // =========================================================================
  // 1. LINGUAGENS, CÓDIGOS E SUAS TECNOLOGIAS
  // =========================================================================
  {
    id: 'lingua-portuguesa',
    name: 'Língua Portuguesa',
    area: 'LINGUAGENS',
    areaLabel: 'Linguagens, Códigos e suas Tecnologias',
    icon: 'BookText',
    color: 'from-blue-600 to-indigo-700',
    description: 'Interpretação, gêneros, gramática aplicada, coesão, coerência e estratégias argumentativas no ENEM.',
    totalTopics: 12,
    completedTopics: 4,
    masteryPercentage: 68,
    topics: [
      createTopic(
        'lp-01',
        'Interpretação de textos',
        'Língua Portuguesa',
        'LINGUAGENS',
        'A interpretação textual no ENEM avalia a capacidade do candidato de apreender sentidos explícitos e implícitos, identificar o interlocutor, o contexto comunicativo e a intenção persuasiva.',
        [
          'Leitura atenta dos enunciados e dos textos de apoio.',
          'Diferenciação entre compreensão (o que está no texto) e interpretação (o que se deduz dele).',
          'Atenção às pistas contextuais, ironias e pressupostos.',
        ],
        ['Compreensão vs Interpretação', 'Estratégias de Leitura', 'Pistas Contextuais', 'Sentidos Implícitos'],
        [
          { front: 'O que diferencia compreensão de interpretação textual?', back: 'Compreensão foca nas informações explícitas presentes no texto; interpretação envolve inferências e conclusões baseadas nas pistas contextuais.' },
          { front: 'Como identificar o interlocutor privilegiado de um texto no ENEM?', back: 'Analisando a linguagem utilizada, o veículo de publicação e o objetivo comunicativo pretendido.' },
        ],
        [
          {
            title: 'Inferência de Tese em Editorial',
            statement: 'Em um artigo de opinião que discute a mobilidade urbana, o autor cita o aumento de ciclovias como sintoma de avanço ecológico. Qual é a tese principal?',
            resolution: 'A tese é que o transporte sustentável depende de políticas públicas integradas que priorizem o cidadão.',
            steps: ['Identificar o ponto de vista central defendido pelo autor', 'Descartar argumentos secundários ou dados ilustrativos', 'Sintetizar o propósito persuasivo'],
          },
        ]
      ),
      createTopic('lp-02', 'Gêneros textuais', 'Língua Portuguesa', 'LINGUAGENS', 'Reconhecimento das características dos gêneros: cartas, notícias, crônicas, charges, resenhas e verbetes.', ['Função social de cada gênero', 'Estrutura padrão e flexibilidade'], ['Gêneros Jornalísticos', 'Gêneros Literários', 'Gêneros Digitais'], [{ front: 'O que define um gênero textual?', back: 'Sua função social, propósito comunicativo e situação de uso recorrente na sociedade.' }], []),
      createTopic('lp-03', 'Tipologia textual', 'Língua Portuguesa', 'LINGUAGENS', 'Distinção entre narração, dissertação, descrição, injunção e exposição.', ['Injunção: textos instrucionais e manuais', 'Dissertação-argumentativa: foco do ENEM'], ['Narrativo', 'Dissertativo', 'Descritivo', 'Injuntivo'], [], []),
      createTopic('lp-04', 'Gramática aplicada ao texto', 'Língua Portuguesa', 'LINGUAGENS', 'A gramática não é cobrada de forma mecânica, mas em função do sentido: concordância, regência e pontuação.', ['Uso expressivo da pontuação', 'Conectivos oracionais'], ['Sintaxe', 'Morfologia Textual', 'Regência & Concordância'], [], []),
      createTopic('lp-05', 'Semântica', 'Língua Portuguesa', 'LINGUAGENS', 'Polissemia, sinonímia, antonímia, hiponímia e hiperonímia no contexto.', ['Sentido denotativo vs conotativo', 'Evolução dos significados'], ['Conotação', 'Denotação', 'Ambiguidade', 'Polissemia'], [], []),
      createTopic('lp-06', 'Figuras de linguagem', 'Língua Portuguesa', 'LINGUAGENS', 'Metáfora, metonímia, antítese, paradoxo, hipérbole, eufemismo, personificação e ironia.', ['Expressividade estética e persuasiva', 'Recurso em campanhas e poesias'], ['Figuras de Pensamento', 'Figuras de Palavras', 'Figuras de Sintaxe'], [], []),
      createTopic('lp-07', 'Funções da linguagem', 'Língua Portuguesa', 'LINGUAGENS', 'Referencial, emotiva, conativa (apelativa), fática, metalinguística e poética.', ['Associação aos elementos da comunicação de Jakobson'], ['Emissor (Emotiva)', 'Receptor (Conativa)', 'Mensagem (Poética)', 'Código (Metalinguística)'], [], []),
      createTopic('lp-08', 'Variação linguística', 'Língua Portuguesa', 'LINGUAGENS', 'Variações regionais (diatópicas), sociais (diastráticas), históricas (diacrônicas) e situacionais (diafásicas).', ['Combate ao preconceito linguístico', 'Adequação ao contexto'], ['Regional', 'Social', 'Histórica', 'Estilística'], [], []),
      createTopic('lp-09', 'Coesão e coerência', 'Língua Portuguesa', 'LINGUAGENS', 'Mecanismos de articulação frasal: anáfora, catáfora, conectivos argumentativos e manutenção temática.', ['Progressão textual sem contradições'], ['Coesão Referencial', 'Coesão Sequencial', 'Coerência Global'], [], []),
      createTopic('lp-10', 'Intertextualidade', 'Língua Portuguesa', 'LINGUAGENS', 'Diálogo entre textos: paródia, paráfrase, epígrafe, alusão e pastiche.', ['Reconhecimento de referências culturais'], ['Paródia (Subversão)', 'Paráfrase (Confirmação)', 'Alusão'], [], []),
      createTopic('lp-11', 'Argumentação', 'Língua Portuguesa', 'LINGUAGENS', 'Tipos de argumentos: autoridade, evidência (dados), consenso, causa e efeito, e exemplificação.', ['Identificação de falácias argumentativas'], ['Estratégias Argumentativas', 'Tipos de Argumentos', 'Contra-argumentação'], [], []),
      createTopic('lp-12', 'Linguagem verbal e não verbal', 'Língua Portuguesa', 'LINGUAGENS', 'Análise combinada de textos multimodais: cartazes publicitários, tirinhas, infográficos e memes.', ['A imagem como recurso de significação'], ['Multimodalidade', 'Charges & Tiras', 'Infográficos'], [], []),
    ],
  },
  {
    id: 'literatura',
    name: 'Literatura',
    area: 'LINGUAGENS',
    areaLabel: 'Linguagens, Códigos e suas Tecnologias',
    icon: 'Feather',
    color: 'from-indigo-600 to-purple-700',
    description: 'Movimentos literários brasileiros, modernismo, autores clássicos e análise poética crítica.',
    totalTopics: 10,
    completedTopics: 3,
    masteryPercentage: 55,
    topics: [
      createTopic('lit-01', 'Escolas literárias', 'Literatura', 'LINGUAGENS', 'Panorama da literatura ocidental e brasileira desde o Quinhentismo até o Contemporâneo.', ['Estilo de época vs Estilo individual'], ['Linha do Tempo', 'Contexto Histórico'], [], []),
      createTopic('lit-02', 'Romantismo', 'Literatura', 'LINGUAGENS', 'As três gerações da poesia romântica e a prosa indigenista, urbana e regionalista.', ['1ª Geração: Nacionalismo e indianismo', '2ª Geração: Ultrarromantismo e mal do século', '3ª Geração: Condoreirismo'], ['Gonçalves Dias', 'Álvares de Azevedo', 'Castro Alves', 'José de Alencar'], [], []),
      createTopic('lit-03', 'Realismo', 'Literatura', 'LINGUAGENS', 'Machado de Assis e a crítica à hipocrisia burguesa através do foco narrativo em primeira pessoa.', ['Ironia fina e pessimismo machadiano'], ['Memórias Póstumas', 'Dom Casmurro', 'Quincas Borba'], [], []),
      createTopic('lit-04', 'Naturalismo', 'Literatura', 'LINGUAGENS', 'Aluísio Azevedo e a teoria do determinismo biológico e social na obra O Cortiço.', ['Zoomorfização dos personagens'], ['O Cortiço', 'Determinismo Social'], [], []),
      createTopic('lit-05', 'Parnasianismo', 'Literatura', 'LINGUAGENS', 'Arte pela arte, rigor métrico, rimas ricas e temática greco-romana.', ['Tríade parnasiana: Olavo Bilac, Raimundo Correia, Alberto de Oliveira'], ['Métrica Rigorosa', 'Forma Fixa'], [], []),
      createTopic('lit-06', 'Simbolismo', 'Literatura', 'LINGUAGENS', 'Cruz e Sousa e Alphonsus de Guimaraens: musicalidade, sinestesia, espiritualismo e pessimismo.', ['Poesia hermética e transcendente'], ['Cruz e Sousa', 'Sinestesia'], [], []),
      createTopic('lit-07', 'Modernismo', 'Literatura', 'LINGUAGENS', 'Semana de Arte Moderna de 1922, 1ª fase (destruição e liberdade), 2ª fase (poesia de 30 e romance regionalista) e 3ª fase (concretismo e formalismo).', ['Mário de Andrade, Oswald, Drummond, Graciliano Ramos'], ['Fase Heroica (1922)', 'Fase de Consolidação (1930)', 'Geração de 45'], [], []),
      createTopic('lit-08', 'Literatura contemporânea', 'Literatura', 'LINGUAGENS', 'Pluralidade de vozes, literatura marginal, poesia visual, autoficção e questões de identidade.', ['Carolina Maria de Jesus, Conceição Evaristo'], ['Vozes Marginais', 'Hibridismo de Gêneros'], [], []),
      createTopic('lit-09', 'Autores brasileiros', 'Literatura', 'LINGUAGENS', 'Estudo aprofundado dos cânones cobrados pelo ENEM.', ['Machado de Assis', 'Carlos Drummond de Andrade', 'Clarice Lispector'], ['Machado', 'Drummond', 'Clarice', 'Guimarães Rosa'], [], []),
      createTopic('lit-10', 'Análise de poemas e obras', 'Literatura', 'LINGUAGENS', 'Recursos estilísticos, ritmo, rima, eu lírico e interpretação simbólica.', ['Relação forma e conteúdo'], ['Métrica', 'Eu Lírico', 'Imagens Poéticas'], [], []),
    ],
  },
  {
    id: 'ingles',
    name: 'Inglês',
    area: 'LINGUAGENS',
    areaLabel: 'Linguagens, Códigos e suas Tecnologias',
    icon: 'Languages',
    color: 'from-cyan-600 to-blue-700',
    description: 'Leitura instrumental, vocabulário contextual, charges, artigos e inferência textual.',
    totalTopics: 7,
    completedTopics: 5,
    masteryPercentage: 85,
    topics: [
      createTopic('ing-01', 'Interpretação', 'Inglês', 'LINGUAGENS', 'Técnicas de Skimming e Scanning para localização de ideias principais e dados específicos.', ['Foco nas palavras cognatas e palavras-chave'], ['Skimming', 'Scanning', 'Topic Sentence'], [], []),
      createTopic('ing-02', 'Vocabulário contextual', 'Inglês', 'LINGUAGENS', 'Dedução de significados por contexto sem uso de dicionário.', ['Prefixos e sufixos reveladores'], ['Context Clues', 'Word Formation'], [], []),
      createTopic('ing-03', 'Charges', 'Inglês', 'LINGUAGENS', 'Humor crítico, ironia e elementos visuais associados ao texto em inglês.', ['Temas globais: política, tecnologia e meio ambiente'], ['Cartoons', 'Irony', 'Visual Humor'], [], []),
      createTopic('ing-04', 'Textos publicitários', 'Inglês', 'LINGUAGENS', 'Campanhas de conscientização, slogans e apelo ao leitor.', ['Verbos no imperativo e adjetivos enfáticos'], ['Advertisements', 'Slogans', 'Imperative'], [], []),
      createTopic('ing-05', 'Notícias', 'Inglês', 'LINGUAGENS', 'Estrutura da notícia jornalística internacional: Lead (Who, What, Where, When, Why, How).', ['Jornais como BBC, The Guardian, NYT'], ['News Reports', 'Headlines', 'Inverted Pyramid'], [], []),
      createTopic('ing-06', 'Música', 'Inglês', 'LINGUAGENS', 'Letras de canções com conteúdo social, figuras de linguagem e rimas.', ['Intertextualidade com o momento histórico'], ['Song Lyrics', 'Rhyme & Rhythm'], [], []),
      createTopic('ing-07', 'Inferência textual', 'Inglês', 'LINGUAGENS', 'Compreensão de ideias subentendidas pelo autor em artigos acadêmicos ou resenhas.', ['Tom do autor (crítico, neutro, elogioso)'], ['Author Tone', 'Implied Meaning'], [], []),
    ],
  },
  {
    id: 'espanhol',
    name: 'Espanhol',
    area: 'LINGUAGENS',
    areaLabel: 'Linguagens, Códigos e suas Tecnologias',
    icon: 'Globe',
    color: 'from-amber-600 to-red-600',
    description: 'Compreensão leitora, heterossemânticos (falsos amigos), tirinhas de Mafalda e cultura hispânica.',
    totalTopics: 7,
    completedTopics: 4,
    masteryPercentage: 70,
    topics: [
      createTopic('esp-01', 'Interpretação', 'Espanhol', 'LINGUAGENS', 'Compreensão global de textos em língua espanhola e identificação de propósitos comunicativos.', ['Cuidado com semelhanças ilusórias com o português'], ['Comprensión Lectora', 'Estratégias de Lectura'], [], []),
      createTopic('esp-02', 'Vocabulário contextual', 'Espanhol', 'LINGUAGENS', 'Sentido de palavras e expressões idiomáticas no contexto de uso.', ['Expressões populares latino-americanas'], ['Léxico Contextual', 'Modismos'], [], []),
      createTopic('esp-03', 'Falsos cognatos', 'Espanhol', 'LINGUAGENS', 'Heterossemânticos: embaraçada, exquisito, rato, largo, zurdo, apellido, etc.', ['Palavras com grafia similar mas sentido totalmente diverso'], ['Heterosemánticos', 'Falsos Amigos Clássicos'], [], []),
      createTopic('esp-04', 'Charges', 'Espanhol', 'LINGUAGENS', 'Tirinhas de Quino (Mafalda), Liniers (Macanudo) e cartuns de crítica social.', ['Ironia reflexiva e humor inteligente'], ['Historietas', 'Mafalda', 'Sátira'], [], []),
      createTopic('esp-05', 'Notícias', 'Espanhol', 'LINGUAGENS', 'Textos de veículos hispano-americanos como El País, Clarín e BBC Mundo.', ['Economia, ecologia e avanços científicos'], ['Titulares', 'Prensa Hispana'], [], []),
      createTopic('esp-06', 'Literatura', 'Espanhol', 'LINGUAGENS', 'Trechos de Gabriel García Márquez, Jorge Luis Borges, Eduardo Galeano e poetas hispânicos.', ['Realismo mágico e denúncia social'], ['Realismo Mágico', 'Autores Latinoamericanos'], [], []),
      createTopic('esp-07', 'Inferência textual', 'Espanhol', 'LINGUAGENS', 'Deduções a partir de artigos de opinião e crônicas contemporâneas.', ['Postura do enunciador'], ['Inferencias', 'Sentidos Ocultos'], [], []),
    ],
  },
  {
    id: 'artes',
    name: 'Artes',
    area: 'LINGUAGENS',
    areaLabel: 'Linguagens, Códigos e suas Tecnologias',
    icon: 'Palette',
    color: 'from-pink-600 to-rose-700',
    description: 'Vanguardas europeias, modernismo brasileiro, arte contemporânea, música, dança e patrimônio cultural.',
    totalTopics: 7,
    completedTopics: 3,
    masteryPercentage: 60,
    topics: [
      createTopic('art-01', 'História da arte', 'Artes', 'LINGUAGENS', 'Evolução artística da pré-história ao renascimento e barroco brasileiro.', ['Aleijadinho e o barroco mineiro'], ['Barroco', 'Renascimento', 'Patrimônio Histórico'], [], []),
      createTopic('art-02', 'Arte brasileira', 'Artes', 'LINGUAGENS', 'Tarsila do Amaral, Anita Malfatti, Cândido Portinari e Di Cavalcanti.', ['Manifesto Antropofágico e identidade nacional'], ['Antropofagia', 'Portinari', 'Tarsila'], [], []),
      createTopic('art-03', 'Vanguardas', 'Artes', 'LINGUAGENS', 'Cubismo, Futurismo, Expressionismo, Dadaísmo e Surrealismo no ENEM.', ['Ruptura com o modelo acadêmico tradicional'], ['Vanguardas Europeias', 'Ruptura Estética'], [], []),
      createTopic('art-04', 'Música', 'Artes', 'LINGUAGENS', 'MPB, Bossa Nova, Tropicália, Samba, Baião e Funk como manifestação social.', ['Música de protesto e censura na ditadura'], ['Tropicália', 'Bossa Nova', 'Identidade Sonora'], [], []),
      createTopic('art-05', 'Teatro', 'Artes', 'LINGUAGENS', 'Teatro de Arena, Teatro do Oprimido (Augusto Boal) e dramaturgia nacional.', ['Arte como reflexão política'], ['Teatro do Oprimido', 'Boal', 'Dramaturgia'], [], []),
      createTopic('art-06', 'Dança', 'Artes', 'LINGUAGENS', 'Dança contemporânea, danças folclóricas brasileiras (Frevo, Maracatu, Catira).', ['Expressão corporal e diversidade regional'], ['Dança Popular', 'Expressão do Corpo'], [], []),
      createTopic('art-07', 'Cultura popular', 'Artes', 'LINGUAGENS', 'Cordel, xilogravura, artesanato e festas populares como patrimônio imaterial.', ['Reconhecimento pelo IPHAN'], ['Cordel', 'Xilogravura', 'Patrimônio Imaterial'], [], []),
    ],
  },
  {
    id: 'educacao-fisica',
    name: 'Educação Física',
    area: 'LINGUAGENS',
    areaLabel: 'Linguagens, Códigos e suas Tecnologias',
    icon: 'Activity',
    color: 'from-emerald-600 to-teal-700',
    description: 'Corpo, saúde, padrões de beleza, práticas corporais, esportes e inclusão social.',
    totalTopics: 5,
    completedTopics: 4,
    masteryPercentage: 80,
    topics: [
      createTopic('ef-01', 'Corpo e saúde', 'Educação Física', 'LINGUAGENS', 'Padrões estéticos impostos pela mídia, vigorexia, sedentarismo e benefícios da atividade regular.', ['Crítica à mercantilização do corpo'], ['Padrões Estéticos', 'Saúde Pública', 'Corpo Mídia'], [], []),
      createTopic('ef-02', 'Esporte', 'Educação Física', 'LINGUAGENS', 'Esporte educacional, de rendimento e de participação; doping e ética esportiva.', ['Dimensões sociais do esporte'], ['Esporte Inclusivo', 'Fair Play', 'Doping'], [], []),
      createTopic('ef-03', 'Cultura corporal', 'Educação Física', 'LINGUAGENS', 'Jogos, brincadeiras tradicionais e lutas (Capoeira como patrimônio cultural imaterial).', ['Resgate de tradições lúdicas'], ['Capoeira', 'Jogos Tradicionais'], [], []),
      createTopic('ef-04', 'Qualidade de vida', 'Educação Física', 'LINGUAGENS', 'Equilíbrio biopsicossocial, ergonomia no trabalho e prevenção de doenças crônicas.', ['Atividade física como direito'], ['Ergonomia', 'Longevidade Saudável'], [], []),
      createTopic('ef-05', 'Inclusão', 'Educação Física', 'LINGUAGENS', 'Esporte adaptado, jogos paralímpicos e acessibilidade para pessoas com deficiência.', ['A superação do capacitismo'], ['Paralimpíadas', 'Acessibilidade'], [], []),
    ],
  },
  {
    id: 'tic',
    name: 'Tecnologias da Informação e Comunicação',
    area: 'LINGUAGENS',
    areaLabel: 'Linguagens, Códigos e suas Tecnologias',
    icon: 'Laptop',
    color: 'from-teal-600 to-cyan-700',
    description: 'Cultura digital, redes sociais, inteligência artificial, fake news e exclusão digital.',
    totalTopics: 5,
    completedTopics: 3,
    masteryPercentage: 75,
    topics: [
      createTopic('tic-01', 'Cultura digital', 'Tecnologias da Informação e Comunicação', 'LINGUAGENS', 'Transformações nas formas de ler, escrever e se relacionar na era da internet.', ['Hipertexto e leitura não linear'], ['Hipertexto', 'Cibercultura', 'Letramento Digital'], [], []),
      createTopic('tic-02', 'Comunicação', 'Tecnologias da Informação e Comunicação', 'LINGUAGENS', 'Novos formatos de mídia, podcasts, streaming e convergência midiática.', ['Horizontalização da produção de conteúdo'], ['Convergência Midiática', 'Podcasts'], [], []),
      createTopic('tic-03', 'Redes sociais', 'Tecnologias da Informação e Comunicação', 'LINGUAGENS', 'Algoritmos, bolhas informacionais, polarização e monetização da atenção.', ['Economia da atenção e impactos na saúde mental'], ['Bolhas Digitais', 'Algoritmos', 'Pegada Digital'], [], []),
      createTopic('tic-04', 'Tecnologia e sociedade', 'Tecnologias da Informação e Comunicação', 'LINGUAGENS', 'Exclusão digital, inteligência artificial, automação do trabalho e cidadania digital.', ['Acesso democratizado à rede como direito'], ['IA no Cotidiano', 'Inclusão Digital'], [], []),
      createTopic('tic-05', 'Linguagem digital', 'Tecnologias da Informação e Comunicação', 'LINGUAGENS', 'Internetês, emojis, memes e novas convenções semióticas na rede.', ['Adequação da linguagem ao suporte digital'], ['Memes', 'Internetês', 'Semiótica Digital'], [], []),
    ],
  },

  // =========================================================================
  // 2. CIÊNCIAS HUMANAS E SUAS TECNOLOGIAS
  // =========================================================================
  {
    id: 'historia',
    name: 'História',
    area: 'CIENCIAS_HUMANAS',
    areaLabel: 'Ciências Humanas e suas Tecnologias',
    icon: 'Hourglass',
    color: 'from-amber-700 to-orange-800',
    description: 'História do Brasil colonial ao contemporâneo, história geral, guerras, revoluções e cidadania.',
    totalTopics: 17,
    completedTopics: 6,
    masteryPercentage: 62,
    topics: [
      createTopic('his-01', 'História do Brasil', 'História', 'CIENCIAS_HUMANAS', 'Visão cronológica e temática das continuidades e rupturas na formação do povo e das instituições brasileiras.', ['Mão de obra, concentração fundiária e exclusão política'], ['Linha do Tempo Brasil', 'Estrutura Social'], [], []),
      createTopic('his-02', 'Brasil Colônia', 'História', 'CIENCIAS_HUMANAS', 'Pacto colonial, economia açucareira, ciclo do ouro, invasões holandesas e revoltas nativistas/emancipacionistas.', ['Inconfidência Mineira e Conjuração Baiana'], ['Pacto Colonial', 'Tráfico Negreiro', 'Ciclo do Ouro'], [], []),
      createTopic('his-03', 'Brasil Império', 'História', 'CIENCIAS_HUMANAS', 'Primeiro Reinado, Período Regencial, Segundo Reinado, Guerra do Paraguai e a crise da monarquia escravista.', ['Constituição outorgada de 1824 e Poder Moderador'], ['Poder Moderador', 'Regências', 'Café & Escravidão'], [], []),
      createTopic('his-04', 'República', 'História', 'CIENCIAS_HUMANAS', 'República da Espada, República Oligárquica (café com leite, coronelismo, voto de cabresto) e revoltas sociais.', ['Revolta da Vacina, Chibata e Canudos'], ['Coronelismo', 'Voto de Cabresto', 'Revoltas da República Velha'], [], []),
      createTopic('his-05', 'Era Vargas', 'História', 'CIENCIAS_HUMANAS', 'Revolução de 30, Governo Provisório, Constitucional, Estado Novo (1937-1945), CLT e propaganda política (DIP).', ['Trabalhismo, nacionalismo e autoritarismo varguista'], ['Estado Novo', 'CLT', 'DIP', 'Nacional-desenvolvimentismo'], [], []),
      createTopic('his-06', 'Ditadura Militar', 'História', 'CIENCIAS_HUMANAS', 'Golpe de 1964, Atos Institucionais (AI-5), milagre econômico, censura, tortura, guerrilha e abertura lenta e gradual.', ['Lei da Anistia de 1979'], ['AI-5', 'Milagre Econômico', 'Censura', 'Diretas Já'], [], []),
      createTopic('his-07', 'Redemocratização', 'História', 'CIENCIAS_HUMANAS', 'Diretas Já, Constituição Cidadã de 1988, Plano Real, impeachment de Collor e governos recentes.', ['A conquista dos direitos sociais e cidadania'], ['Constituição de 1988', 'Plano Real', 'Democracia Jovem'], [], []),
      createTopic('his-08', 'Escravidão', 'História', 'CIENCIAS_HUMANAS', 'O tráfico transatlântico, resistência negra, quilombos (Palmares), leis abolicionistas tardias e o pós-abolição excludente.', ['Heranças estruturais do racismo no Brasil'], ['Navio Negreiro', 'Quilombo dos Palmares', 'Leis Abolicionistas'], [], []),
      createTopic('his-09', 'História indígena', 'História', 'CIENCIAS_HUMANAS', 'Sociedades pré-cabralinas, genocídio, etnocídio, missões jesuíticas, demarcação de terras e direitos na Constituição de 88.', ['Protagonismo dos povos originários'], ['Povos Originários', 'Demarcação de Terras', 'Artigo 231'], [], []),
      createTopic('his-10', 'História africana', 'História', 'CIENCIAS_HUMANAS', 'Reinos e impérios africanos (Mali, Songai, Congo), diversidade cultural pré-colonial e diáspora atlântica.', ['Lei 10.639/03 e valorização cultural'], ['Império do Mali', 'Diáspora Africana', 'Matriz Cultural'], [], []),
      createTopic('his-11', 'Antiguidade', 'História', 'CIENCIAS_HUMANAS', 'Grécia (democracia ateniense e pólis) e Roma (República, Império, direito romano e crise do escravismo).', ['Cidadania na Antiguidade vs Cidadania Moderna'], ['Democracia Ateniense', 'Pólis', 'Pax Romana'], [], []),
      createTopic('his-12', 'Idade Média', 'História', 'CIENCIAS_HUMANAS', 'Feudalismo, suserania e vassalagem, poder teocêntrico da Igreja Católica, Cruzadas e renascimento comercial/urbano.', ['Peste Negra e crise do século XIV'], ['Feudalismo', 'Igreja Medieval', 'Cruzadas'], [], []),
      createTopic('his-13', 'Idade Moderna', 'História', 'CIENCIAS_HUMANAS', 'Renascimento cultural, Grandes Navegações, Reformas Religiosas, Absolutismo monárquico e Mercantilismo.', ['Antropocentrismo e nova visão científica'], ['Absolutismo', 'Grandes Navegações', 'Reforma Protestante'], [], []),
      createTopic('his-14', 'Revoluções', 'História', 'CIENCIAS_HUMANAS', 'Revolução Industrial (impactos no trabalho e urbanização) e Revolução Francesa (Iluminismo, queda do Antigo Regime).', ['Burguesia e proletariado'], ['Revolução Industrial', 'Revolução Francesa', 'Iluminismo'], [], []),
      createTopic('his-15', 'Guerras Mundiais', 'História', 'CIENCIAS_HUMANAS', '1ª Guerra (imperialismo e trincheiras) e 2ª Guerra (ascensão nazi-fascista, Holocausto e bombas atômicas).', ['Criação da ONU e direitos humanos'], ['Tratado de Versalhes', 'Fascismo & Nazismo', 'Holocausto'], [], []),
      createTopic('his-16', 'Guerra Fria', 'História', 'CIENCIAS_HUMANAS', 'Bipolaridade mundial (EUA vs URSS), corrida armamentista e espacial, Doutrina Truman, Muro de Berlim e crises periféricas.', ['Queda do Muro e fim da URSS (1991)'], ['Bipolaridade', 'Cortina de Ferro', 'Crise dos Mísseis'], [], []),
      createTopic('his-17', 'História contemporânea', 'História', 'CIENCIAS_HUMANAS', 'Nova ordem mundial multipolar, terrorismo internacional (11 de setembro), Primavera Árabe e crises migratórias.', ['Desafios da democracia no século XXI'], ['Globalização', 'Multipolaridade', 'Tensões Geopolíticas'], [], []),
    ],
  },
  {
    id: 'geografia',
    name: 'Geografia',
    area: 'CIENCIAS_HUMANAS',
    areaLabel: 'Ciências Humanas e suas Tecnologias',
    icon: 'MapPin',
    color: 'from-emerald-700 to-green-900',
    description: 'Geografia física, relevo, clima, urbanização, geopolítica global, agropecuária e meio ambiente.',
    totalTopics: 17,
    completedTopics: 7,
    masteryPercentage: 74,
    topics: [
      createTopic('geo-01', 'Cartografia', 'Geografia', 'CIENCIAS_HUMANAS', 'Escala numérica e gráfica, curvas de nível, projeções cartográficas (Mercator vs Peters) e sensoriamento remoto.', ['Distorções nas projeções e ideologias'], ['Escala', 'Projeções Cartográficas', 'Sensoriamento Remoto'], [], []),
      createTopic('geo-02', 'Geografia física', 'Geografia', 'CIENCIAS_HUMANAS', 'Tectônica de placas, agentes internos (vulcanismo, terremotos) e externos do relevo (intemperismo e erosão).', ['Dinâmica geológica terrestre'], ['Tectonismo', 'Intemperismo', 'Erosão'], [], []),
      createTopic('geo-03', 'Clima', 'Geografia', 'CIENCIAS_HUMANAS', 'Fatores e elementos climáticos, climas do Brasil (Equatorial, Tropical, Semiárido, Subtropical) e fenômenos (El Niño e La Niña).', ['Aquecimento global e eventos extremos'], ['Massas de Ar', 'Climogramas', 'El Niño'], [], []),
      createTopic('geo-04', 'Relevo', 'Geografia', 'CIENCIAS_HUMANAS', 'Planalto, planície, depressão e estruturas geológicas do Brasil (bacias sedimentares e crátons).', ['Classificação de Aziz Ab’Saber e Jurandyr Ross'], ['Planalto', 'Planície', 'Depressão'], [], []),
      createTopic('geo-05', 'Vegetação', 'Geografia', 'CIENCIAS_HUMANAS', 'Domínios morfoclimáticos do Brasil: Amazônia, Cerrado, Caatinga, Mata Atlântica, Pampas e Pantanal.', ['Hotspots de biodiversidade e desmatamento'], ['Domínios Morfoclimáticos', 'Cerrado', 'Amazônia'], [], []),
      createTopic('geo-06', 'Hidrografia', 'Geografia', 'CIENCIAS_HUMANAS', 'Bacias hidrográficas do Brasil (Amazonas, Tocantins-Araguaia, São Francisco e Paraná) e crise hídrica.', ['Uso da água na agricultura e matriz energética'], ['Bacias Hidrográficas', 'Aquíferos', 'Transposição'], [], []),
      createTopic('geo-07', 'Urbanização', 'Geografia', 'CIENCIAS_HUMANAS', 'Metropolização, conurbação, megalópoles, gentrificação, segregação socioespacial e problemas urbanos.', ['Mobilidade, saneamento e moradia'], ['Conurbação', 'Gentrificação', 'Segregação'], [], []),
      createTopic('geo-08', 'População', 'Geografia', 'CIENCIAS_HUMANAS', 'Transição demográfica, pirâmides etárias, taxa de fecundidade, envelhecimento populacional e bônus demográfico.', ['Impactos na previdência social'], ['Transição Demográfica', 'Pirâmide Etária'], [], []),
      createTopic('geo-09', 'Migrações', 'Geografia', 'CIENCIAS_HUMANAS', 'Migrações internas no Brasil (êxodo rural, transumância, migração de retorno) e fluxos internacionais de refugiados.', ['Xenofobia e barreiras fronteiriças'], ['Êxodo Rural', 'Refugiados', 'Xenofobia'], [], []),
      createTopic('geo-10', 'Globalização', 'Geografia', 'CIENCIAS_HUMANAS', 'Meio técnico-científico-informacional de Milton Santos, aldeia global e desigualdades centro-periferia.', ['Fluxos materiais e imateriais'], ['Meio Técnico-Científico', 'Milton Santos'], [], []),
      createTopic('geo-11', 'Economia', 'Geografia', 'CIENCIAS_HUMANAS', 'Divisão Internacional do Trabalho (DIT), transnacionais e dependência econômica.', ['Commodities e balança comercial'], ['DIT', 'Transnacionais', 'Commodities'], [], []),
      createTopic('geo-12', 'Indústria', 'Geografia', 'CIENCIAS_HUMANAS', 'Modelos produtivos (Taylorismo, Fordismo, Toyotismo, Indústria 4.0) e desconcentração industrial no Brasil.', ['Revoluções Industriais'], ['Fordismo', 'Toyotismo', 'Desconcentração Industrial'], [], []),
      createTopic('geo-13', 'Agropecuária', 'Geografia', 'CIENCIAS_HUMANAS', 'Agronegócio, fronteira agrícola (MATOPIBA), agricultura familiar, concentração de terras e conflitos no campo.', ['Segurança alimentar vs exportação'], ['Agronegócio', 'MATOPIBA', 'Agricultura Familiar'], [], []),
      createTopic('geo-14', 'Energia', 'Geografia', 'CIENCIAS_HUMANAS', 'Fontes renováveis (hidrelétrica, eólica, solar, biomassa) e não renováveis (petróleo, carvão, gás, nuclear).', ['Transição energética e matriz brasileira'], ['Matriz Energética', 'Energias Limpas', 'Pré-Sal'], [], []),
      createTopic('geo-15', 'Meio ambiente', 'Geografia', 'CIENCIAS_HUMANAS', 'Pegada ecológica, efeito estufa, ilhas de calor, inversão térmica, chuva ácida, arenização e acordos climáticos.', ['Conferências do Clima (COP)'], ['Efeito Estufa', 'Inversão Térmica', 'COP'], [], []),
      createTopic('geo-16', 'Geopolítica', 'Geografia', 'CIENCIAS_HUMANAS', 'Conflitos territoriais, disputa por recursos estratégicos, hegemonia dos EUA e ascensão chinesa.', ['Tensões no Oriente Médio e no Leste Europeu'], ['Disputas Territoriais', 'Hegemonia Global'], [], []),
      createTopic('geo-17', 'Blocos econômicos', 'Geografia', 'CIENCIAS_HUMANAS', 'Mercosul, União Europeia, USMCA, BRICS e níveis de integração econômica (zona de livre comércio a união monetária).', ['Protecionismo vs Livre Comércio'], ['Mercosul', 'União Europeia', 'BRICS'], [], []),
    ],
  },
  {
    id: 'filosofia',
    name: 'Filosofia',
    area: 'CIENCIAS_HUMANAS',
    areaLabel: 'Ciências Humanas e suas Tecnologias',
    icon: 'Brain',
    color: 'from-purple-800 to-indigo-950',
    description: 'Pensamento grego, ética, política moderna, contratualismo, iluminismo e filosofia contemporânea.',
    totalTopics: 12,
    completedTopics: 5,
    masteryPercentage: 70,
    topics: [
      createTopic('fil-01', 'Filosofia antiga', 'Filosofia', 'CIENCIAS_HUMANAS', 'Passagem do mito ao lógos, pré-socráticos (arché e cosmologia) e atitude filosófica.', ['Origem da razão ocidental na Grécia'], ['Mito ao Lógos', 'Pré-Socráticos', 'Arché'], [], []),
      createTopic('fil-02', 'Sócrates', 'Filosofia', 'CIENCIAS_HUMANAS', 'Método socrático: ironia e maiêutica; "Só sei que nada sei"; ética e busca pela virtude interior.', ['Ocupação com a vida na pólis'], ['Maiêutica', 'Ironia', 'Conhece-te a ti mesmo'], [], []),
      createTopic('fil-03', 'Platão', 'Filosofia', 'CIENCIAS_HUMANAS', 'Mito da Caverna, Teoria das Ideias (Mundo Sensível vs Mundo Inteligível) e a República (Rei Filósofo).', ['Reminiscência e dualismo corpo-alma'], ['Mito da Caverna', 'Mundo das Ideias', 'A República'], [], []),
      createTopic('fil-04', 'Aristóteles', 'Filosofia', 'CIENCIAS_HUMANAS', 'Ética a Nicômaco (justo meio), teleologia, ato e potência, quatro causas e homem como animal político.', ['Empirismo inicial e virtude como hábito'], ['Justo Meio', 'Ato e Potência', 'Zoon Politikon'], [], []),
      createTopic('fil-05', 'Filosofia medieval', 'Filosofia', 'CIENCIAS_HUMANAS', 'Patrística (Santo Agostinho: fé e razão, tempo, livre-arbítrio) e Escolástica (São Tomás de Aquino: cinco vias de Deus).', ['Harmonização entre cristianismo e filosofia greco-romana'], ['Agostinho', 'Tomás de Aquino', 'Fé & Razão'], [], []),
      createTopic('fil-06', 'Filosofia moderna', 'Filosofia', 'CIENCIAS_HUMANAS', 'Ruptura científica (Copérnico, Galileu), Maquiavel e a autonomia da política ("os fins justificam os meios").', ['Secularização do pensamento'], ['Maquiavel', 'Virtù e Fortuna', 'Revolução Científica'], [], []),
      createTopic('fil-07', 'Racionalismo', 'Filosofia', 'CIENCIAS_HUMANAS', 'René Descartes: dúvida metódica, "Penso, logo existo" (Cogito ergo sum), ideias inatas e dualismo cartesiano.', ['A razão como fonte segura de conhecimento'], ['Descartes', 'Dúvida Metódica', 'Cogito'], [], []),
      createTopic('fil-08', 'Empirismo', 'Filosofia', 'CIENCIAS_HUMANAS', 'John Locke (tábula rasa), David Hume (crítica à causalidade) e Francis Bacon (método indutivo).', ['A experiência sensível como limite do saber'], ['Tábula Rasa', 'Locke', 'Hume'], [], []),
      createTopic('fil-09', 'Iluminismo', 'Filosofia', 'CIENCIAS_HUMANAS', 'Kant (Esclarecimento, imperativo categórico), Rousseau, Voltaire e Montesquieu (divisão dos três poderes).', ['Sapere aude (ouse saber) e autonomia moral'], ['Kant', 'Imperativo Categórico', 'Divisão dos Poderes'], [], []),
      createTopic('fil-10', 'Ética', 'Filosofia', 'CIENCIAS_HUMANAS', 'Diferença entre moral (costumes sociais) e ética (reflexão crítica sobre a conduta), utilitarismo vs deontologia.', ['Dilemas morais contemporâneos'], ['Ética Deontológica', 'Utilitarismo', 'Moral'], [], []),
      createTopic('fil-11', 'Política', 'Filosofia', 'CIENCIAS_HUMANAS', 'Contratualismo: Estado de Natureza e Contrato Social em Hobbes (Leviatã), Locke (Propriedade) e Rousseau (Vontade Geral).', ['Legitimidade do poder do Estado'], ['Hobbes', 'Locke', 'Rousseau', 'Contrato Social'], [], []),
      createTopic('fil-12', 'Filosofia contemporânea', 'Filosofia', 'CIENCIAS_HUMANAS', 'Nietzsche (crítica à moral cristã, super-homem), Escola de Frankfurt (Indústria Cultural), Hannah Arendt (Banalidade do Mal) e Foucault (Biopolítica).', ['Crítica da razão instrumental'], ['Foucault', 'Arendt', 'Nietzsche', 'Escola de Frankfurt'], [], []),
    ],
  },
  {
    id: 'sociologia',
    name: 'Sociologia',
    area: 'CIENCIAS_HUMANAS',
    areaLabel: 'Ciências Humanas e suas Tecnologias',
    icon: 'Users',
    color: 'from-amber-800 to-yellow-950',
    description: 'Clássicos da sociologia (Marx, Durkheim, Weber), cultura, cidadania, trabalho e movimentos sociais.',
    totalTopics: 13,
    completedTopics: 6,
    masteryPercentage: 78,
    topics: [
      createTopic('soc-01', 'Cultura', 'Sociologia', 'CIENCIAS_HUMANAS', 'Conceito antropológico de cultura, etnocentrismo, relativismo cultural e patrimônio cultural.', ['Combate a visões eurocêntricas e preconceitos'], ['Etnocentrismo', 'Relativismo Cultural', 'Diversidade'], [], []),
      createTopic('soc-02', 'Sociedade', 'Sociologia', 'CIENCIAS_HUMANAS', 'Os clássicos: Émile Durkheim (Fato Social, solidariedade mecânica e orgânica, anomia).', ['Exterioridade, coercitividade e generalidade'], ['Durkheim', 'Fato Social', 'Solidariedade'], [], []),
      createTopic('soc-03', 'Cidadania', 'Sociologia', 'CIENCIAS_HUMANAS', 'Direitos civis, políticos e sociais de T. H. Marshall; cidadania de papel de Gilberto Dimenstein.', ['Evolução histórica e conquista de direitos no Brasil'], ['Direitos Civis', 'Políticos', 'Sociais', 'Marshall'], [], []),
      createTopic('soc-04', 'Trabalho', 'Sociologia', 'CIENCIAS_HUMANAS', 'Karl Marx: mais-valia, alienação, luta de classes e modo de produção capitalista.', ['Transformações contemporâneas: precarização e uberização'], ['Marx', 'Mais-Valia', 'Alienação', 'Uberização'], [], []),
      createTopic('soc-05', 'Desigualdade', 'Sociologia', 'CIENCIAS_HUMANAS', 'Desigualdade social, racial e de gênero; concentração de renda, Índice de Gini e mobilidade social.', ['Estratificação social no Brasil'], ['Índice de Gini', 'Concentração de Renda'], [], []),
      createTopic('soc-06', 'Classes sociais', 'Sociologia', 'CIENCIAS_HUMANAS', 'Max Weber: ação social, tipos ideais, ética protestante e estratificação multidimensional (classe, status e poder).', ['Racionalização do mundo moderno'], ['Weber', 'Ação Social', 'Ética Protestante'], [], []),
      createTopic('soc-07', 'Movimentos sociais', 'Sociologia', 'CIENCIAS_HUMANAS', 'Movimentos tradicionais (operário, camponês) e novos movimentos sociais (negro, feminista, LGBTQIA+, ambientalista).', ['Papel na conquista e garantia de políticas públicas'], ['Movimento Negro', 'Feminismo', 'Ação Coletiva'], [], []),
      createTopic('soc-08', 'Estado', 'Sociologia', 'CIENCIAS_HUMANAS', 'Monopólio legítimo da força física segundo Weber, Estado liberal, Estado de bem-estar social e neoliberalismo.', ['Funções e limites do poder estatal'], ['Monopólio da Violência', 'Welfare State', 'Neoliberalismo'], [], []),
      createTopic('soc-09', 'Política', 'Sociologia', 'CIENCIAS_HUMANAS', 'Democracia representativa, participativa e deliberativa; participação popular e representatividade.', ['Crise de representatividade no mundo contemporâneo'], ['Democracia Participativa', 'Voto Consciente'], [], []),
      createTopic('soc-10', 'Globalização', 'Sociologia', 'CIENCIAS_HUMANAS', 'Sociedade em rede de Manuel Castells, modernidade líquida de Zygmunt Bauman e consumo desenfreado.', ['Fragilização dos vínculos humanos'], ['Bauman', 'Modernidade Líquida', 'Sociedade em Rede'], [], []),
      createTopic('soc-11', 'Indústria cultural', 'Sociologia', 'CIENCIAS_HUMANAS', 'Adorno e Horkheimer: padronização da arte, entretenimento de massa e conformismo social.', ['Crítica à manipulação das consciências'], ['Adorno & Horkheimer', 'Cultura de Massa'], [], []),
      createTopic('soc-12', 'Identidade', 'Sociologia', 'CIENCIAS_HUMANAS', 'Stuart Hall e a fragmentação das identidades na pós-modernidade; pertencimento e alteridade.', ['Descentramento do sujeito moderno'], ['Stuart Hall', 'Identidade Cultural'], [], []),
      createTopic('soc-13', 'Diversidade', 'Sociologia', 'CIENCIAS_HUMANAS', 'Pluralidade étnica, intolerância religiosa, direitos humanos e leis de proteção às minorias.', ['Respeito às diferenças como pilar democrático'], ['Pluralidade', 'Direitos Humanos', 'Tolerância'], [], []),
    ],
  },

  // =========================================================================
  // 3. CIÊNCIAS DA NATUREZA E SUAS TECNOLOGIAS
  // =========================================================================
  {
    id: 'biologia',
    name: 'Biologia',
    area: 'CIENCIAS_DA_NATUREZA',
    areaLabel: 'Ciências da Natureza e suas Tecnologias',
    icon: 'Dna',
    color: 'from-green-600 to-emerald-800',
    description: 'Ecologia, genética, citologia, fisiologia humana, evolução, imunologia e biotecnologia no ENEM.',
    totalTopics: 18,
    completedTopics: 8,
    masteryPercentage: 82,
    topics: [
      createTopic('bio-01', 'Citologia', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Organelas celulares e suas funções, membrana plasmática (transporte ativo e passivo, osmose) e divisão celular (mitose e meiose).', ['Células eucariontes vs procariontes'], ['Membrana Plasmática', 'Mitose & Meiose', 'Organelas'], [], []),
      createTopic('bio-02', 'Bioquímica', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Água, sais minerais, carboidratos, lipídios, proteínas (enzimas e desnaturação) e ácidos nucleicos (DNA e RNA).', ['Papel biológico das macromoléculas'], ['Proteínas', 'Enzimas', 'Ácidos Nucleicos'], [], []),
      createTopic('bio-03', 'Metabolismo', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Fotossíntese (fase clara e escura), quimiossíntese, respiração celular aeróbica e fermentação (alcoólica e láctica).', ['Balanço energético do ATP'], ['Fotossíntese', 'Respiração Celular', 'Fermentação'], [], []),
      createTopic('bio-04', 'Genética', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Primeira e Segunda Lei de Mendel, codominância, heredogramas, grupos sanguíneos (sistema ABO e Rh) e herança ligada ao sexo.', ['Cálculos de probabilidades genéticas'], ['Mendel', 'Sistema ABO', 'Herança Ligada ao Sexo'], [], []),
      createTopic('bio-05', 'Biotecnologia', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'DNA recombinante, transgênicos, clonagem, células-tronco, PCR, teste de DNA e vacinas de RNA.', ['Aplicações na saúde e na agricultura'], ['Transgênicos', 'CRISPR', 'Clonagem', 'Células-Tronco'], [], []),
      createTopic('bio-06', 'Evolução', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Lamarckismo vs Darwinismo/Neodarwinismo: seleção natural, mutações, recombinação gênica, especiação e resistências.', ['Resistência bacteriana a antibióticos como seleção'], ['Seleção Natural', 'Neodarwinismo', 'Especiação'], [], []),
      createTopic('bio-07', 'Ecologia', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Tema mais cobrado no ENEM! Níveis de organização, habitat, nicho ecológico, pirâmides ecológicas e biomas.', ['Fluxo unidirecional de energia'], ['Nicho Ecológico', 'Pirâmides de Energia', 'Biomas'], [], []),
      createTopic('bio-08', 'Cadeias alimentares', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Produtores, consumidores e decompositores; teias tróficas e bioacumulação/magnificação trófica de metais pesados.', ['Toxinas acumuladas no topo da cadeia'], ['Níveis Tróficos', 'Bioacumulação', 'Teias Alimentares'], [], []),
      createTopic('bio-09', 'Relações ecológicas', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Intraespecíficas e interespecíficas, harmônicas (mutualismo, comensalismo) e desarmônicas (predatismo, parasitismo, competição).', ['Controle biológico de pragas'], ['Mutualismo', 'Competição', 'Controle Biológico'], [], []),
      createTopic('bio-10', 'Botânica', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Grupos vegetais (briófitas, pteridófitas, gimnospermas, angiospermas), tecidos condutores, fitormônios e transpiração.', ['Adaptações xerofíticas da Caatinga'], ['Angiospermas', 'Transpiração Vegetal', 'Hormônios'], [], []),
      createTopic('bio-11', 'Zoologia', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Invertebrados (artrópodes como vetores de doenças) e vertebrados (peixes, anfíbios, répteis, aves e mamíferos).', ['Adaptações evolutivas ao ambiente terrestre'], ['Artrópodes', 'Vetores de Doenças', 'Vertebrados'], [], []),
      createTopic('bio-12', 'Fisiologia humana', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Sistemas digestório, respiratório, circulatório, excretor, nervoso e endócrino (hormônios como insulina e glucagon).', ['Homeostase do organismo humano'], ['Digestão', 'Circulação', 'Insulina & Diabetes'], [], []),
      createTopic('bio-13', 'Imunologia', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Diferença entre vacina (preventiva, antígenos, memória) e soro (curativo, anticorpos prontos); resposta primária e secundária.', ['Imunização e saúde pública'], ['Vacina vs Soro', 'Anticorpos', 'Memória Imunológica'], [], []),
      createTopic('bio-14', 'Microbiologia', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Bactérias, fungos, protozoários e vírus na indústria alimentícia e na ecologia (decomposição e ciclo do nitrogênio).', ['Fixação de nitrogênio por leguminosas'], ['Ciclo do Nitrogênio', 'Bactérias Benéficas'], [], []),
      createTopic('bio-15', 'Vírus', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Estrutura viral (DNA ou RNA), ciclo lítico e lisogênico, viroses comuns (Dengue, Febre Amarela, COVID-19, HIV e Gripe).', ['Controle de vetores como o Aedes aegypti'], ['Viroses', 'Ciclo Viral', 'Aedes aegypti'], [], []),
      createTopic('bio-16', 'Bactérias', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Morfologia bacteriana, reprodução por fissão binária, recombinação (conjugação) e doenças (tétano, tuberculose, cólera).', ['Uso correto de antibióticos'], ['Bactérias', 'Resistência Antibiótica'], [], []),
      createTopic('bio-17', 'Parasitologia', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Doenças causadas por vermes (esquistossomose, teníase, cisticercose, ascaridíase) e protozoários (Chagas, malária, leishmaniose).', ['Ciclo de vida e medidas profiláticas'], ['Esquistossomose', 'Doença de Chagas', 'Profilaxia'], [], []),
      createTopic('bio-18', 'Meio ambiente', 'Biologia', 'CIENCIAS_DA_NATUREZA', 'Eutrofização das águas, desmatamento, queimadas, poluição do ar e perda da biodiversidade.', ['Desenvolvimento sustentável e biorremediação'], ['Eutrofização', 'Biorremediação', 'Pegada Ecológica'], [], []),
    ],
  },
  {
    id: 'quimica',
    name: 'Química',
    area: 'CIENCIAS_DA_NATUREZA',
    areaLabel: 'Ciências da Natureza e suas Tecnologias',
    icon: 'FlaskConical',
    color: 'from-blue-700 to-cyan-800',
    description: 'Estequiometria, soluções, química orgânica, termoquímica, eletroquímica e química ambiental.',
    totalTopics: 17,
    completedTopics: 5,
    masteryPercentage: 55,
    topics: [
      createTopic('qui-01', 'Química geral', 'Química', 'CIENCIAS_DA_NATUREZA', 'Estados físicos da matéria, mudanças de estado, substâncias puras e misturas (homogêneas e heterogêneas), e métodos de separação.', ['Filtração, decantação, destilação simples e fracionada'], ['Métodos de Separação', 'Destilação', 'Misturas'], [], []),
      createTopic('qui-02', 'Estrutura atômica', 'Química', 'CIENCIAS_DA_NATUREZA', 'Modelos atômicos (Dalton, Thomson, Rutherford, Bohr), número atômico, massa, isótopos e distribuição eletrônica.', ['Transições eletrônicas e emissão de luz'], ['Modelos Atômicos', 'Bohr', 'Distribuição Eletrônica'], [], []),
      createTopic('qui-03', 'Tabela periódica', 'Química', 'CIENCIAS_DA_NATUREZA', 'Organização em famílias e períodos; propriedades periódicas: raio atômico, eletronegatividade e energia de ionização.', ['Metais, ametais e gases nobres'], ['Eletronegatividade', 'Raio Atômico', 'Propriedades Periódicas'], [], []),
      createTopic('qui-04', 'Ligações químicas', 'Química', 'CIENCIAS_DA_NATUREZA', 'Ligação iônica, covalente (polar e apolar) e metálica; forças intermoleculares (ligações de hidrogênio e dipolo induzido).', ['Ponto de fusão e solubilidade baseado em interações'], ['Ligação Iônica', 'Ligação Covalente', 'Pontes de Hidrogênio'], [], []),
      createTopic('qui-05', 'Funções inorgânicas', 'Química', 'CIENCIAS_DA_NATUREZA', 'Ácidos, bases, sais e óxidos; conceitos de Arrhenius e Lewis; reações de neutralização e chuva ácida.', ['Óxidos ácidos e estufa'], ['Ácidos & Bases', 'Óxidos', 'Neutralização'], [], []),
      createTopic('qui-06', 'Estequiometria', 'Química', 'CIENCIAS_DA_NATUREZA', 'Massa molar, constante de Avogadro, pureza de reagentes, rendimento de reações e reagente limitante/excesso.', ['Cálculos em reações de combustão'], ['Massa Molar', 'Rendimento', 'Reagente Limitante'], [], []),
      createTopic('qui-07', 'Soluções', 'Química', 'CIENCIAS_DA_NATUREZA', 'Soluto e solvente, curva de solubilidade, soluções saturadas, insaturadas e supersaturadas.', ['Diluição e mistura de soluções'], ['Solubilidade', 'Curvas de Solubilidade'], [], []),
      createTopic('qui-08', 'Concentração', 'Química', 'CIENCIAS_DA_NATUREZA', 'Concentração comum (g/L), molaridade (mol/L), título (% em massa), partes por milhão (ppm) e densidade.', ['Cálculos aplicados a medicamentos e poluição'], ['Molaridade', 'PPM', 'Diluição'], [], []),
      createTopic('qui-09', 'Termoquímica', 'Química', 'CIENCIAS_DA_NATUREZA', 'Reações endotérmicas e exotérmicas, entalpia (ΔH), Lei de Hess, energia de ligação e calor de combustão.', ['Eficiência energética dos combustíveis (etanol vs gasolina)'], ['Entalpia', 'Lei de Hess', 'Calor de Combustão'], [], []),
      createTopic('qui-10', 'Cinética', 'Química', 'CIENCIAS_DA_NATUREZA', 'Velocidade das reações, teoria das colisões, energia de ativação e fatores de aceleração (temperatura, superfície, catalisador).', ['Catalisadores reduzem a energia de ativação'], ['Energia de Ativação', 'Catalisador', 'Velocidade'], [], []),
      createTopic('qui-11', 'Equilíbrio químico', 'Química', 'CIENCIAS_DA_NATUREZA', 'Constante de equilíbrio (Kc e Kp), Princípio de Le Chatelier (deslocamento por temperatura, pressão e concentração).', ['Síntese da amônia pelo processo Haber-Bosch'], ['Le Chatelier', 'Kc & Kp', 'Deslocamento de Equilíbrio'], [], []),
      createTopic('qui-12', 'pH', 'Química', 'CIENCIAS_DA_NATUREZA', 'Equilíbrio iônico da água (Kw), cálculo de pH e pOH, escala de acidez, indicadores ácido-base e hidrólise salina.', ['pH do sangue e tamponamento'], ['Escala de pH', 'pOH', 'Solução Tampão'], [], []),
      createTopic('qui-13', 'Eletroquímica', 'Química', 'CIENCIAS_DA_NATUREZA', 'Pilhas galvânicas (potencial de redução, ânodo, cátodo, ponte salina) e eletrólise (obtenção de metais e tratamento de efluentes).', ['Proteção contra corrosão e pilhas recarregáveis'], ['Pilha de Daniell', 'Ânodo & Cátodo', 'Eletrólise'], [], []),
      createTopic('qui-14', 'Radioatividade', 'Química', 'CIENCIAS_DA_NATUREZA', 'Emissões alfa, beta e gama; tempo de meia-vida, datação por Carbono-14, fissão nuclear e fusão estelar.', ['Acidentes radioativos (Césio-137) e energia nuclear'], ['Meia-Vida', 'Carbono-14', 'Fissão Nuclear'], [], []),
      createTopic('qui-15', 'Química orgânica', 'Química', 'CIENCIAS_DA_NATUREZA', 'Classificação de cadeias carbônicas, hidrocarbonetos, álcoois, aldeídos, cetonas, ácidos carboxílicos, ésteres e aminas.', ['Nomenclatura IUPAC e propriedades dos compostos'], ['Funções Orgânicas', 'Cadeias Carbônicas', 'IUPAC'], [], []),
      createTopic('qui-16', 'Polímeros', 'Química', 'CIENCIAS_DA_NATUREZA', 'Polímeros de adição e condensação, plásticos (PET, PVC, PE), borrachas, reciclagem e bioplásticos biodegradáveis.', ['Impacto ambiental do descarte de plásticos'], ['Polímeros', 'Plásticos', 'Reciclagem'], [], []),
      createTopic('qui-17', 'Química ambiental', 'Química', 'CIENCIAS_DA_NATUREZA', 'Camada de ozônio e CFCs, chuva ácida (SOx e NOx), efeito estufa (CO2 e metano), tratamento de água e esgoto.', ['Química verde e sustentabilidade'], ['Chuva Ácida', 'Tratamento de Água', 'Química Verde'], [], []),
    ],
  },
  {
    id: 'fisica',
    name: 'Física',
    area: 'CIENCIAS_DA_NATUREZA',
    areaLabel: 'Ciências da Natureza e suas Tecnologias',
    icon: 'Atom',
    color: 'from-blue-900 to-indigo-900',
    description: 'Mecânica clássica, eletricidade, termologia, ondas, óptica e energia no contexto cotidiano.',
    totalTopics: 18,
    completedTopics: 4,
    masteryPercentage: 48,
    topics: [
      createTopic('fis-01', 'Cinemática', 'Física', 'CIENCIAS_DA_NATUREZA', 'MRU e MRUV, gráficos de movimento (posição, velocidade, aceleração), lançamento vertical e queda livre.', ['Equação de Torricelli e interpretação gráfica'], ['MRU & MRUV', 'Gráficos Cinemáticos', 'Torricelli'], [], []),
      createTopic('fis-02', 'Dinâmica', 'Física', 'CIENCIAS_DA_NATUREZA', 'Forças fundamentais, força peso, força normal, força de atrito (estático e dinâmico) e força elástica (Lei de Hooke).', ['Diagramas de corpo livre'], ['Força de Atrito', 'Lei de Hooke', 'Plano Inclinado'], [], []),
      createTopic('fis-03', 'Leis de Newton', 'Física', 'CIENCIAS_DA_NATUREZA', '1ª Lei (Inércia e cintos de segurança), 2ª Lei (F = m.a) e 3ª Lei (Ação e Reação).', ['Aplicações na segurança no trânsito'], ['Inércia', 'F = m.a', 'Ação e Reação'], [], []),
      createTopic('fis-04', 'Trabalho', 'Física', 'CIENCIAS_DA_NATUREZA', 'Trabalho de uma força constante, teorema do trabalho e energia cinética, potência mecânica e rendimento.', ['Trabalho motor e trabalho resistente'], ['Trabalho Mecânico', 'Potência', 'Rendimento'], [], []),
      createTopic('fis-05', 'Energia', 'Física', 'CIENCIAS_DA_NATUREZA', 'Energia cinética, energia potencial gravitacional e elástica; conservação da energia mecânica.', ['Dissipação de energia por atrito'], ['Energia Mecânica', 'Conservação de Energia'], [], []),
      createTopic('fis-06', 'Potência', 'Física', 'CIENCIAS_DA_NATUREZA', 'Potência útil, total e dissipada; relação com tempo de execução e consumo energético em Joules e kWh.', ['Cálculo de consumo em aparelhos elétricos'], ['Potência Watts', 'Consumo kWh'], [], []),
      createTopic('fis-07', 'Gravitação', 'Física', 'CIENCIAS_DA_NATUREZA', 'Leis de Kepler (órbitas elípticas, lei das áreas, lei dos períodos) e Lei da Gravitação Universal de Newton.', ['Satélites geoestacionários e marés'], ['Leis de Kepler', 'Gravitação Universal'], [], []),
      createTopic('fis-08', 'Hidrostática', 'Física', 'CIENCIAS_DA_NATUREZA', 'Densidade e massa específica, pressão hidrostática (Teorema de Stevin), Princípio de Pascal (prensas hidráulicas) e Arquimedes (Empuxo).', ['Por que os navios de ferro flutuam'], ['Pressão', 'Empuxo', 'Princípio de Pascal'], [], []),
      createTopic('fis-09', 'Termologia', 'Física', 'CIENCIAS_DA_NATUREZA', 'Diferença entre calor e temperatura, escalas termométricas (Celsius e Kelvin) e dilatação térmica dos sólidos e líquidos.', ['Juntas de dilatação em pontes e trilhos'], ['Calor vs Temperatura', 'Dilatação Térmica'], [], []),
      createTopic('fis-10', 'Calorimetria', 'Física', 'CIENCIAS_DA_NATUREZA', 'Calor sensível (Q = m.c.ΔT), calor latente (Q = m.L), trocas de calor sem perdas e curvas de aquecimento.', ['Capacidade térmica e brisas marítimas'], ['Calor Sensível', 'Calor Latente', 'Trocas de Calor'], [], []),
      createTopic('fis-11', 'Ondulatória', 'Física', 'CIENCIAS_DA_NATUREZA', 'Equação fundamental da onda (v = λ.f), ondas mecânicas e eletromagnéticas, transversais e longitudinais.', ['Espectro eletromagnético: do rádio aos raios gama'], ['v = λ.f', 'Espectro Eletromagnético', 'Ondas'], [], []),
      createTopic('fis-12', 'Acústica', 'Física', 'CIENCIAS_DA_NATUREZA', 'Qualidades fisiológicas do som (altura/frequência, intensidade/amplitude, timbre) e Efeito Doppler na sirene da ambulância.', ['Poluição sonora e decibéis'], ['Efeito Doppler', 'Timbre vs Altura', 'Decibéis'], [], []),
      createTopic('fis-13', 'Óptica', 'Física', 'CIENCIAS_DA_NATUREZA', 'Reflexão e refração da luz, Lei de Snell-Descartes, espelhos planos e esféricos, lentes corretivas para miopia e hipermetropia.', ['Fibra óptica e reflexão total'], ['Refração', 'Lentes e Miopia', 'Fibra Óptica'], [], []),
      createTopic('fis-14', 'Eletricidade', 'Física', 'CIENCIAS_DA_NATUREZA', 'Carga elétrica, processos de eletrização (atrito, contato, indução), Lei de Coulomb e campo elétrico.', ['Raios e para-raios'], ['Eletrização', 'Lei de Coulomb'], [], []),
      createTopic('fis-15', 'Circuitos', 'Física', 'CIENCIAS_DA_NATUREZA', 'Primeira e Segunda Lei de Ohm (U = R.i e R = ρ.L/A), circuitos em série e paralelo, disjuntores, fusíveis e potência elétrica (P = U.i).', ['Cálculo da conta de luz mensal'], ['Leis de Ohm', 'Circuitos Paralelos', 'Potência P = U.i'], [], []),
      createTopic('fis-16', 'Magnetismo', 'Física', 'CIENCIAS_DA_NATUREZA', 'Ímãs e polos magnéticos inseparáveis, campo magnético da Terra e bússolas.', ['Origem do campo magnético terrestre'], ['Polos Magnéticos', 'Campo Magnético'], [], []),
      createTopic('fis-17', 'Eletromagnetismo', 'Física', 'CIENCIAS_DA_NATUREZA', 'Experiência de Oersted, força magnética sobre cargas em movimento (regra da mão direita) e indução eletromagnética de Faraday.', ['Funcionamento de usinas hidrelétricas e transformadores'], ['Lei de Faraday', 'Transformadores', 'Indução'], [], []),
      createTopic('fis-18', 'Física moderna', 'Física', 'CIENCIAS_DA_NATUREZA', 'Efeito fotoelétrico (Einstein), dualidade onda-partícula, radiação de corpo negro e tecnologia de painéis solares.', ['Fótons e energia solar'], ['Efeito Fotoelétrico', 'Painéis Solares', 'Fótons'], [], []),
    ],
  },

  // =========================================================================
  // 4. MATEMÁTICA E SUAS TECNOLOGIAS
  // =========================================================================
  {
    id: 'matematica',
    name: 'Matemática',
    area: 'MATEMATICA',
    areaLabel: 'Matemática e suas Tecnologias',
    icon: 'Calculator',
    color: 'from-amber-500 to-red-600',
    description: 'Matemática básica, funções, geometria plana e espacial, trigonometria, estatística e probabilidade no ENEM.',
    totalTopics: 24,
    completedTopics: 10,
    masteryPercentage: 67,
    topics: [
      createTopic('mat-01', 'Matemática básica', 'Matemática', 'MATEMATICA', 'Números naturais, inteiros, racionais e reais; potenciação, radiciação e ordem das operações.', ['Base para 60% da prova de matemática do ENEM'], ['Operações Básicas', 'Potenciação', 'Múltiplos e Divisores'], [], []),
      createTopic('mat-02', 'Operações', 'Matemática', 'MATEMATICA', 'Agilidade em cálculos aritméticos sem uso de calculadora, notação científica e arredondamentos.', ['Estimativa de resultados em alternativas'], ['Cálculo Rápido', 'Notação Científica'], [], []),
      createTopic('mat-03', 'Frações', 'Matemática', 'MATEMATICA', 'Soma, subtração, multiplicação e divisão de frações, frações equivalentes e números decimais.', ['Conversão fração-decimal-porcentagem'], ['Frações Equivalentes', 'Operações com Frações'], [], []),
      createTopic('mat-04', 'Razão e proporção', 'Matemática', 'MATEMATICA', 'Conceito de razão (velocidade, densidade, escala cartográfica) e grandezas direta e inversamente proporcionais.', ['Escala em maquetes e mapas no ENEM'], ['Grandezas Proporcionais', 'Escala Numérica'], [], []),
      createTopic('mat-05', 'Regra de três', 'Matemática', 'MATEMATICA', 'Regra de três simples e composta com identificação correta das flechas de proporcionalidade.', ['Aplicação cotidiana em receitas, produção e dosagens'], ['Regra de Três Simples', 'Regra Composta'], [], []),
      createTopic('mat-06', 'Porcentagem', 'Matemática', 'MATEMATICA', 'Cálculos de porcentagens diretas, aumentos sucessivos, descontos sucessivos e fator multiplicador.', ['Fator 1 + i e 1 - i'], ['Fator de Aumento', 'Descontos Sucessivos'], [], []),
      createTopic('mat-07', 'Matemática financeira', 'Matemática', 'MATEMATICA', 'Juros simples e compostos, amortização, comparação entre compras à vista com desconto e a prazo.', ['Planejamento financeiro familiar'], ['Juros Simples (J = C.i.t)', 'Juros Compostos M = C(1+i)^t'], [], []),
      createTopic('mat-08', 'Juros', 'Matemática', 'MATEMATICA', 'Fórmulas de capitalização, conversão de taxas mensais e anuais e cálculo de parcelamentos.', ['Taxa real vs taxa nominal'], ['Capitalização', 'Taxas Equivalentes'], [], []),
      createTopic('mat-09', 'Função do 1º grau', 'Matemática', 'MATEMATICA', 'Função afim f(x) = ax + b, taxa de variação (coeficiente angular), termo independente e gráficos de retas.', ['Planos de telefonia e corridas de aplicativo'], ['Coeficiente Angular', 'Zero da Função Afim'], [], []),
      createTopic('mat-10', 'Função do 2º grau', 'Matemática', 'MATEMATICA', 'Função quadrática f(x) = ax² + bx + c, raízes por Bháskara, vértice da parábola (Xv e Yv para valores máximos e mínimos).', ['Trajetória de projéteis e lucros máximos'], ['Vértice da Parábola', 'Máximos e Mínimos', 'Bhaskara'], [], []),
      createTopic('mat-11', 'Função exponencial', 'Matemática', 'MATEMATICA', 'Crescimento e decaimento exponencial, gráficos e equações exponenciais.', ['Crescimento bacteriano e propagação viral'], ['Crescimento Exponencial', 'Gráfico Exponencial'], [], []),
      createTopic('mat-12', 'Logaritmos', 'Matemática', 'MATEMATICA', 'Definição de logaritmo, propriedades operatórias (produto, quociente, potência), mudança de base e escala Richter/pH.', ['Resolução de equações com expoentes desconhecidos'], ['Propriedades dos Logs', 'Escala Richter'], [], []),
      createTopic('mat-13', 'Progressões', 'Matemática', 'MATEMATICA', 'Progressão Aritmética (PA) e Progressão Geométrica (PG): termo geral e soma dos termos.', ['Padrões de repetição em sequências numéricas'], ['Termo Geral da PA', 'Soma da PG'], [], []),
      createTopic('mat-14', 'Equações', 'Matemática', 'MATEMATICA', 'Modelagem matemática de problemas do cotidiano através de equações algébricas.', ['Tradução da linguagem verbal para a algébrica'], ['Modelagem Algébrica', 'Equações de 1º Grau'], [], []),
      createTopic('mat-15', 'Sistemas', 'Matemática', 'MATEMATICA', 'Sistemas lineares 2x2 e 3x3: métodos de adição, substituição e interpretação geométrica das retas.', ['Ponto de intersecção entre trajetórias'], ['Método da Adição', 'Interpretação Gráfica'], [], []),
      createTopic('mat-16', 'Geometria plana', 'Matemática', 'MATEMATICA', 'Áreas de triângulos, quadriláteros, círculos e polígonos regulares; Teorema de Pitágoras e semelhança de triângulos.', ['Cálculo de pisos, gramados e revestimentos'], ['Pitágoras', 'Área do Círculo', 'Semelhança de Triângulos'], [], []),
      createTopic('mat-17', 'Geometria espacial', 'Matemática', 'MATEMATICA', 'Prismas, cubos, paralelepípedos, cilindros, cones, pirâmides e esferas: cálculo de área superficial e volume.', ['Capacidade de caixas d’água e embalagens em litros'], ['Volume de Cilindros', 'Paralelepípedos', 'Cones & Esferas'], [], []),
      createTopic('mat-18', 'Geometria analítica', 'Matemática', 'MATEMATICA', 'Distância entre dois pontos no plano cartesiano, ponto médio, equação da reta e equação da circunferência.', ['GPS e localização espacial'], ['Distância entre Pontos', 'Equação da Reta'], [], []),
      createTopic('mat-19', 'Trigonometria', 'Matemática', 'MATEMATICA', 'Razões trigonométricas no triângulo retângulo (seno, cosseno e tangente), ângulos notáveis (30°, 45°, 60°), Lei dos Senos e Cossenos.', ['Medição de alturas inacessíveis'], ['Seno, Cosseno & Tangente', 'Ciclo Trigonométrico'], [], []),
      createTopic('mat-20', 'Estatística', 'Matemática', 'MATEMATICA', 'Interpretação de gráficos e tabelas, variáveis quantitativas e qualitativas, frequência absoluta e relativa.', ['Essencial no ENEM para leitura crítica de dados'], ['Frequência Relativa', 'Leitura de Gráficos'], [], []),
      createTopic('mat-21', 'Média, moda e mediana', 'Matemática', 'MATEMATICA', 'Medidas de tendência central: média aritmética simples e ponderada, moda (valor mais frequente) e mediana (valor central ordenado).', ['Diferença entre as medidas em distribuições assimétricas'], ['Média Ponderada', 'Mediana', 'Moda'], [], []),
      createTopic('mat-22', 'Probabilidade', 'Matemática', 'MATEMATICA', 'Espaço amostral, eventos favoráveis, probabilidade da união de eventos, probabilidade condicional e eventos independentes.', ['Jogos de loteria e testes médicos'], ['Casos Favoráveis / Casos Possíveis', 'Probabilidade Condicional'], [], []),
      createTopic('mat-23', 'Análise combinatória', 'Matemática', 'MATEMATICA', 'Princípio Fundamental da Contagem (PFC), arranjos, permutações simples e com repetição, e combinações simples.', ['Quando a ordem dos elementos importa ou não'], ['PFC', 'Combinação Simples', 'Permutações'], [], []),
      createTopic('mat-24', 'Gráficos e tabelas', 'Matemática', 'MATEMATICA', 'Leitura e extração de dados em gráficos de barras, colunas, setores (pizza), linhas e histogramas.', ['Cruzar informações de diferentes eixos'], ['Gráfico de Setores', 'Histogramas', 'Tendências em Linhas'], [], []),
    ],
  },
];
