import { Question, Simulado, EssayTopic, Achievement, User, StudentProfile } from '../types';

export const SEED_USERS: { user: User; profile?: StudentProfile }[] = [
  {
    user: {
      id: 'usr-admin-erick',
      name: 'Erick Siqueira',
      email: 'ericksiqueiraa@gmail.com',
      role: 'ADMINISTRADOR',
      status: 'APROVADO',
      city: 'São Paulo',
      state: 'SP',
      phone: '(11) 99999-9999',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
      createdAt: '2026-01-01T08:00:00.000Z',
    },
  },
  {
    user: {
      id: 'usr-admin-erick-2',
      name: 'erick',
      email: 'ericksiqueiraaa@gmail.com',
      role: 'ADMINISTRADOR',
      status: 'APROVADO',
      city: 'São Paulo',
      state: 'SP',
      phone: '(11) 99999-9999',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
      createdAt: '2026-01-01T08:00:00.000Z',
    },
  },
  {
    user: {
      id: 'usr-aluno-aprovado',
      name: 'Lucas Gabriel Silveira',
      email: 'aluno@enem2026.com.br',
      role: 'ALUNO',
      status: 'APROVADO',
      objective: 'ENEM',
      city: 'São Paulo',
      state: 'SP',
      phone: '(11) 98765-4321',
      document: '423.891.758-92',
      birthDate: '2008-04-12',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
      createdAt: '2026-01-15T10:00:00.000Z',
    },
    profile: {
      id: 'prof-01',
      userId: 'usr-aluno-aprovado',
      birthDate: '2008-04-12',
      state: 'SP',
      city: 'São Paulo',
      school: 'Colégio Estadual Santos Dumont',
      targetCourse: 'Medicina',
      targetUniversity: 'USP / UNICAMP',
      targetScore: 820,
      studyHoursPerDay: 4,
      studyDaysPerWeek: 6,
      difficultSubjects: ['Química', 'Física', 'Redação'],
      examDate: '2026-11-08',
      onboardingCompleted: true,
      streakDays: 15,
      lastStudyDate: new Date().toISOString().split('T')[0],
      xp: 2850,
      level: 6,
    },
  },
  {
    user: {
      id: 'usr-pendente-01',
      name: 'Mariana Castro Rocha',
      email: 'mariana.rocha@gmail.com',
      role: 'ALUNO',
      status: 'PENDENTE_APROVACAO',
      objective: 'ENEM',
      city: 'Campinas',
      state: 'SP',
      phone: '(19) 99123-4567',
      document: '456.789.012-34',
      birthDate: '2007-06-18',
      createdAt: '2026-09-15T14:30:00.000Z',
    },
  },
  {
    user: {
      id: 'usr-pendente-02',
      name: 'Thiago Henrique Dias',
      email: 'thiago.dias@hotmail.com',
      role: 'ALUNO',
      status: 'PENDENTE_APROVACAO',
      objective: 'ETEC',
      city: 'Santos',
      state: 'SP',
      phone: '(13) 98877-6655',
      document: '321.654.987-00',
      birthDate: '2008-02-22',
      createdAt: '2026-09-15T16:10:00.000Z',
    },
  },
];

export const SEED_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-01',
    code: 'FIRST_QUESTION',
    title: 'Primeiro Passo',
    description: 'Respondeu sua primeira questão no ENEM 2026 PRO.',
    category: 'QUESTOES',
    icon: 'Target',
    xpReward: 50,
  },
  {
    id: 'ach-02',
    code: 'QUESTIONS_50',
    title: 'Rumo aos 800+',
    description: 'Respondeu 50 questões de treino.',
    category: 'QUESTOES',
    icon: 'Flame',
    xpReward: 150,
  },
  {
    id: 'ach-03',
    code: 'STREAK_7',
    title: 'Semana Blindada',
    description: 'Manteve 7 dias consecutivos de ofensiva de estudos.',
    category: 'OFENSIVA',
    icon: 'Zap',
    xpReward: 300,
  },
  {
    id: 'ach-04',
    code: 'FIRST_SIMULADO',
    title: 'Maratonista',
    description: 'Concluiu seu primeiro simulado com análise completa.',
    category: 'SIMULADOS',
    icon: 'Award',
    xpReward: 250,
  },
  {
    id: 'ach-05',
    code: 'FIRST_ESSAY',
    title: 'Autor de Peso',
    description: 'Escreveu e enviou sua primeira redação para correção com IA.',
    category: 'REDACAO',
    icon: 'Feather',
    xpReward: 200,
  },
  {
    id: 'ach-06',
    code: 'ESSAY_800',
    title: 'Redação Elite (800+)',
    description: 'Alcançou 800 pontos ou mais na redação do ENEM.',
    category: 'REDACAO',
    icon: 'Star',
    xpReward: 500,
  },
  {
    id: 'ach-07',
    code: 'MISTAKE_SOLVED',
    title: 'Superação',
    description: 'Dominou uma questão que você havia errado anteriormente.',
    category: 'ESPECIAL',
    icon: 'CheckCircle2',
    xpReward: 100,
  },
];

export const SEED_QUESTIONS: Question[] = [
  // MATEMÁTICA
  {
    id: 'q-mat-01',
    statement: 'Uma empresa de logística calcula o custo total de frete C(x), em reais, para o transporte de mercadorias até uma distância x, em quilômetros, por meio da função afim C(x) = 2,50x + 80,00, em que 80,00 corresponde à taxa fixa de carregamento e 2,50 é o custo por quilômetro rodado. Para um cliente cujo frete totalizou R$ 580,00, qual foi a distância percorrida pelo transporte?',
    supportText: 'A função afim modela custos lineares em transporte e logística com taxa fixa e taxa variável proporcional à quilometragem.',
    options: [
      { letter: 'A', text: '160 km', selectionPercentage: 8 },
      { letter: 'B', text: '180 km', selectionPercentage: 11 },
      { letter: 'C', text: '200 km', selectionPercentage: 74 },
      { letter: 'D', text: '220 km', selectionPercentage: 4 },
      { letter: 'E', text: '240 km', selectionPercentage: 3 },
    ],
    correctOption: 'C',
    explanation: 'Substituindo C(x) = 580 na equação: 580 = 2,50x + 80 -> 2,50x = 580 - 80 -> 2,50x = 500 -> x = 500 / 2,50 = 200 km.',
    area: 'MATEMATICA',
    discipline: 'Matemática',
    topic: 'Funções',
    subtopic: 'Função Afim',
    year: 2024,
    difficulty: 'FACIL',
    source: 'ENEM 2024 (Adaptada)',
    tags: ['Função Afim', 'Álgebra', 'Interpretação'],
    totalAnswers: 342,
    correctAnswersCount: 253,
  },
  {
    id: 'q-mat-02',
    statement: 'Um reservatório cilíndrico de água possui raio da base igual a 2 metros e altura de 5 metros. Devido a uma seca na região, o reservatório estava com 60% de sua capacidade máxima. Considerando pi = 3,14, qual é o volume aproximado de água, em litros, presente no reservatório?',
    supportText: 'Lembre-se de que o volume de um cilindro é dado por V = pi * r^2 * h e que 1 metro cúbico equivale a 1.000 litros.',
    options: [
      { letter: 'A', text: '37.680 litros', selectionPercentage: 68 },
      { letter: 'B', text: '42.800 litros', selectionPercentage: 12 },
      { letter: 'C', text: '62.800 litros', selectionPercentage: 14 },
      { letter: 'D', text: '18.840 litros', selectionPercentage: 4 },
      { letter: 'E', text: '50.240 litros', selectionPercentage: 2 },
    ],
    correctOption: 'A',
    explanation: 'Volume total = pi * r^2 * h = 3,14 * 2^2 * 5 = 3,14 * 4 * 5 = 62,8 m³. Em litros: 62,8 * 1.000 = 62.800 litros. Como contém 60% da capacidade: 0,60 * 62.800 = 37.680 litros.',
    area: 'MATEMATICA',
    discipline: 'Matemática',
    topic: 'Geometria Espacial',
    subtopic: 'Cilindros e Volumes',
    year: 2023,
    difficulty: 'MEDIO',
    source: 'ENEM 2023',
    tags: ['Geometria Espacial', 'Volumes', 'Unidades de Medida'],
    totalAnswers: 289,
    correctAnswersCount: 196,
  },
  {
    id: 'q-mat-03',
    statement: 'Em um grupo de 10 amigos, será sorteada uma comissão de 3 pessoas para organizar a festa de formatura. Se Carlos e Mariana fazem parte desse grupo de 10 pessoas, qual é a probabilidade de que AMBOS façam parte da comissão sorteada?',
    supportText: 'A análise combinatória auxilia na contagem de casos favoráveis e do espaço amostral para cálculo de probabilidade.',
    options: [
      { letter: 'A', text: '1/15', selectionPercentage: 62 },
      { letter: 'B', text: '1/30', selectionPercentage: 18 },
      { letter: 'C', text: '3/10', selectionPercentage: 10 },
      { letter: 'D', text: '1/120', selectionPercentage: 6 },
      { letter: 'E', text: '2/15', selectionPercentage: 4 },
    ],
    correctOption: 'A',
    explanation: 'Espaço amostral: C(10, 3) = (10 * 9 * 8) / (3 * 2 * 1) = 120 comissões possíveis. Casos favoráveis: Carlos e Mariana já estão fixos na comissão, restando escolher 1 membro entre os 8 restantes -> C(8, 1) = 8. Probabilidade = 8 / 120 = 1 / 15.',
    area: 'MATEMATICA',
    discipline: 'Matemática',
    topic: 'Probabilidade',
    subtopic: 'Combinações e Eventos',
    year: 2024,
    difficulty: 'DIFICIL',
    source: 'ENEM 2024',
    tags: ['Probabilidade', 'Análise Combinatória'],
    totalAnswers: 410,
    correctAnswersCount: 254,
  },
  {
    id: 'q-mat-04',
    statement: 'As notas de um estudante nos quatro primeiros bimestres foram: 6,5; 7,0; 8,5 e 6,0. A escola adota média aritmética simples mínima de 7,0 ao final de 5 bimestres para aprovação sem exame final. Qual é a nota mínima que o estudante precisa obter no quinto bimestre para ser aprovado direto?',
    options: [
      { letter: 'A', text: '6,5', selectionPercentage: 5 },
      { letter: 'B', text: '7,0', selectionPercentage: 79 },
      { letter: 'C', text: '7,5', selectionPercentage: 11 },
      { letter: 'D', text: '8,0', selectionPercentage: 3 },
      { letter: 'E', text: '8,5', selectionPercentage: 2 },
    ],
    correctOption: 'B',
    explanation: 'Para média mínima 7,0 em 5 bimestres, a soma total das notas deve ser: 5 * 7,0 = 35,0. A soma das 4 primeiras notas: 6,5 + 7,0 + 8,5 + 6,0 = 28,0. Logo, a nota necessária é: 35,0 - 28,0 = 7,0.',
    area: 'MATEMATICA',
    discipline: 'Matemática',
    topic: 'Estatística',
    subtopic: 'Média Aritmética',
    year: 2024,
    difficulty: 'FACIL',
    source: 'ENEM 2024',
    tags: ['Estatística', 'Média'],
    totalAnswers: 380,
    correctAnswersCount: 300,
  },

  // CIÊNCIAS DA NATUREZA
  {
    id: 'q-nat-01',
    statement: 'Um circuito elétrico residencial de 127 V alimenta um chuveiro elétrico de potência 4.445 W quando operando na posição "Inverno". Qual é a intensidade da corrente elétrica que percorre o disjuntor desse circuito e a resistência elétrica do chuveiro nessas condições?',
    supportText: 'As relações de potência elétrica relacionam P = V * I e V = R * I.',
    options: [
      { letter: 'A', text: '35 A e aproximadamente 3,63 ohms', selectionPercentage: 71 },
      { letter: 'B', text: '30 A e aproximadamente 4,23 ohms', selectionPercentage: 14 },
      { letter: 'C', text: '40 A e aproximadamente 3,18 ohms', selectionPercentage: 8 },
      { letter: 'D', text: '25 A e aproximadamente 5,08 ohms', selectionPercentage: 4 },
      { letter: 'E', text: '50 A e aproximadamente 2,54 ohms', selectionPercentage: 3 },
    ],
    correctOption: 'A',
    explanation: 'Corrente: I = P / V = 4445 / 127 = 35 A. Resistência: R = V / I = 127 / 35 aprox. 3,63 ohms (ou R = V^2 / P = 127^2 / 4445 = 16129 / 4445 aprox. 3,63 ohms).',
    area: 'CIENCIAS_DA_NATUREZA',
    discipline: 'Física',
    topic: 'Eletrodinâmica',
    subtopic: 'Potência e Circuitos',
    year: 2024,
    difficulty: 'MEDIO',
    source: 'ENEM 2024',
    tags: ['Eletrodinâmica', 'Circuitos', 'Energia'],
    totalAnswers: 295,
    correctAnswersCount: 209,
  },
  {
    id: 'q-nat-02',
    statement: 'A biomagnificação (ou magnificação trófica) é o fenômeno em que substâncias tóxicas não biodegradáveis (como metais pesados e agrotóxicos organoclorados) se acumulam em concentrações progressivamente maiores ao longo dos níveis tróficos. Em um ecossistema aquático contaminado por mercúrio, em qual dos seguintes organismos espera-se encontrar a MAIOR concentração do poluente por unidade de biomassa?',
    supportText: 'Cadeia trófica aquática: Fitoplâncton -> Zooplâncton -> Peixes pequenos -> Peixes predadores -> Aves piscívoras.',
    options: [
      { letter: 'A', text: 'Fitoplâncton (produtores primários)', selectionPercentage: 8 },
      { letter: 'B', text: 'Zooplâncton (consumidores primários)', selectionPercentage: 6 },
      { letter: 'C', text: 'Peixes pequenos herbívoros', selectionPercentage: 7 },
      { letter: 'D', text: 'Aves piscívoras (topo de cadeia)', selectionPercentage: 75 },
      { letter: 'E', text: 'Bactérias decompositoras', selectionPercentage: 4 },
    ],
    correctOption: 'D',
    explanation: 'Na magnificação trófica, compostos bioacumulativos não metabolizados nem excretados com facilidade acumulam-se em concentrações crescentes a cada nível trófico. O organismo do topo da cadeia (aves piscívoras) consome grande biomassa dos níveis anteriores, concentrando o maior teor de mercúrio.',
    area: 'CIENCIAS_DA_NATUREZA',
    discipline: 'Biologia',
    topic: 'Ecologia',
    subtopic: 'Cadeias Tróficas e Poluição',
    year: 2023,
    difficulty: 'FACIL',
    source: 'ENEM 2023',
    tags: ['Ecologia', 'Poluição', 'Biomagnificação'],
    totalAnswers: 310,
    correctAnswersCount: 232,
  },
  {
    id: 'q-nat-03',
    statement: 'A queima completa de 1 mol de gás propano (C3H8), muito presente no gás de cozinha (GLP), libera calor segundo a equação termoquímica balanceada: C3H8(g) + 5 O2(g) -> 3 CO2(g) + 4 H2O(l) (Delta H = -2220 kJ/mol). Sabendo que as massas molares são C = 12 g/mol e H = 1 g/mol, qual é a quantidade aproximada de calor liberada pela queima completa de 88 g de propano?',
    options: [
      { letter: 'A', text: '1.110 kJ', selectionPercentage: 9 },
      { letter: 'B', text: '2.220 kJ', selectionPercentage: 15 },
      { letter: 'C', text: '4.440 kJ', selectionPercentage: 70 },
      { letter: 'D', text: '6.660 kJ', selectionPercentage: 4 },
      { letter: 'E', text: '8.880 kJ', selectionPercentage: 2 },
    ],
    correctOption: 'C',
    explanation: 'Massa molar do propano (C3H8): (3 * 12) + (8 * 1) = 36 + 8 = 44 g/mol. A quantidade de matéria em 88 g é: n = 88 / 44 = 2 mols de C3H8. Como 1 mol libera 2220 kJ, 2 mols liberarão: 2 * 2220 = 4.440 kJ de calor.',
    area: 'CIENCIAS_DA_NATUREZA',
    discipline: 'Química',
    topic: 'Termoquímica',
    subtopic: 'Entalpia de Combustão',
    year: 2024,
    difficulty: 'MEDIO',
    source: 'ENEM 2024',
    tags: ['Termoquímica', 'Estequiometria'],
    totalAnswers: 280,
    correctAnswersCount: 196,
  },
  {
    id: 'q-nat-04',
    statement: 'O efeito Doppler é a alteração perceptível na frequência de uma onda sonora emitida por uma fonte em movimento em relação a um observador. Quando uma ambulância com a sirene ligada se APROXIMA de uma pessoa parada na calçada, o som percebido pela pessoa é mais agudo porque:',
    options: [
      { letter: 'A', text: 'A velocidade de propagação do som no ar aumenta consideravelmente.', selectionPercentage: 14 },
      { letter: 'B', text: 'A frequência percebida é maior devido à diminuição do comprimento de onda aparente.', selectionPercentage: 72 },
      { letter: 'C', text: 'A amplitude da onda diminui gerando maior intensidade sonora.', selectionPercentage: 6 },
      { letter: 'D', text: 'O período da onda emitida pela fonte aumenta com a aceleração.', selectionPercentage: 5 },
      { letter: 'E', text: 'A velocidade da ambulância anula as cristas da onda sonora.', selectionPercentage: 3 },
    ],
    correctOption: 'B',
    explanation: 'Na aproximação da fonte em relação ao observador, as frentes de onda se comprimem na direção do movimento (comprimento de onda aparente menor), fazendo com que o observador receba mais cristas por segundo (frequência percebida maior, som mais agudo).',
    area: 'CIENCIAS_DA_NATUREZA',
    discipline: 'Física',
    topic: 'Ondulatória',
    subtopic: 'Efeito Doppler',
    year: 2023,
    difficulty: 'MEDIO',
    source: 'ENEM 2023',
    tags: ['Ondulatória', 'Acústica'],
    totalAnswers: 320,
    correctAnswersCount: 230,
  },

  // CIÊNCIAS HUMANAS
  {
    id: 'q-hum-01',
    statement: 'Durante a Era Vargas (1930-1945), especificamente com a criação da Consolidação das Leis do Trabalho (CLT) em 1943, o Estado brasileiro promoveu uma profunda transformação nas relações entre capital e trabalho. Historicamente, essa política trabalhista varguista caracterizou-se pelo(a):',
    supportText: '"Trabalhadores do Brasil! [...] A vossa cooperação organizada é a garantia da ordem e da prosperidade da Pátria." (Discurso de 1º de Maio de Getúlio Vargas).',
    options: [
      { letter: 'A', text: 'Concessão de ampla autonomia para os sindicatos operários deflagrarem greves.', selectionPercentage: 8 },
      { letter: 'B', text: 'Paternalismo estatal atrelado à tutela e cooptação sindical sob rígido controle governamental.', selectionPercentage: 78 },
      { letter: 'C', text: 'Total privatização do setor produtivo e livre negociação direta sem intermediação da Justiça do Trabalho.', selectionPercentage: 5 },
      { letter: 'D', text: 'Abolição dos direitos previdenciários e estímulo ao modelo liberal clássico de mercado.', selectionPercentage: 5 },
      { letter: 'E', text: 'Aliança estratégica exclusiva com as lideranças camponesas do Nordeste açucareiro.', selectionPercentage: 4 },
    ],
    correctOption: 'B',
    explanation: 'O modelo corporativista e populista varguista conjugava a concessão de direitos sociais (CLT, férias, salário mínimo) com o enquadramento e tutela dos sindicatos pelo Ministério do Trabalho ("sindicatos pelegos"), impedindo a autonomia operária e contendo manifestações radicais.',
    area: 'CIENCIAS_HUMANAS',
    discipline: 'História',
    topic: 'Brasil República',
    subtopic: 'Era Vargas e Trabalhismo',
    year: 2024,
    difficulty: 'MEDIO',
    source: 'ENEM 2024',
    tags: ['História do Brasil', 'Era Vargas', 'Trabalhismo'],
    totalAnswers: 360,
    correctAnswersCount: 280,
  },
  {
    id: 'q-hum-02',
    statement: 'O processo de urbanização brasileiro na segunda metade do século XX foi marcado por intenso êxodo rural e rápido crescimento das metrópoles. Um dos principais reflexos socioespaciais desse modelo foi a macrocefalia urbana e a segregação socioespacial, expressas principalmente por:',
    options: [
      { letter: 'A', text: 'Crescimento desordenado das periferias com precariedade de infraestrutura e serviços básicos.', selectionPercentage: 84 },
      { letter: 'B', text: 'Distribuição homogênea de investimentos públicos entre o centro e as zonas rurais.', selectionPercentage: 4 },
      { letter: 'C', text: 'Desaceleração do setor terciário frente à mecanização acelerada do campo.', selectionPercentage: 5 },
      { letter: 'D', text: 'Eradicação do déficit habitacional mediante planos diretores participativos.', selectionPercentage: 3 },
      { letter: 'E', text: 'Diminuição dos movimentos pendulares diários de trabalhadores.', selectionPercentage: 4 },
    ],
    correctOption: 'A',
    explanation: 'A urbanização acelerada e sem reforma agrária nem planejamento gerou hipertrofia urbana, favelização e segregação socioespacial, nas quais as periferias concentram moradias desprovidas de saneamento, transporte de massa e equipamentos públicos de qualidade.',
    area: 'CIENCIAS_HUMANAS',
    discipline: 'Geografia',
    topic: 'Geografia Urbana',
    subtopic: 'Urbanização Brasileira',
    year: 2023,
    difficulty: 'FACIL',
    source: 'ENEM 2023',
    tags: ['Urbanização', 'Geografia', 'Segregação'],
    totalAnswers: 390,
    correctAnswersCount: 327,
  },
  {
    id: 'q-hum-03',
    statement: 'Segundo a teoria aristotélica da ética, a virtude moral (areté) não é uma inclinação inata, mas um hábito desenvolvido pela prática constante guiada pela reta razão. Aristóteles formula a virtude como a doutrina do "justo meio" (mesotês), que consiste em:',
    supportText: '"A virtude é, pois, uma disposição de caráter relacionada com a escolha e consistente num meio-termo [...] determinado por um princípio racional." (ARISTÓTELES. Ética a Nicômaco).',
    options: [
      { letter: 'A', text: 'Um comportamento neutro que evita tomar decisões morais difíceis.', selectionPercentage: 9 },
      { letter: 'B', text: 'A equidistância equilibrada entre dois extremos viciosos: um por excesso e outro por falta.', selectionPercentage: 77 },
      { letter: 'C', text: 'A busca desenfreada pelos prazeres materiais como finalidade suprema da vida.', selectionPercentage: 5 },
      { letter: 'D', text: 'O cumprimento estrito e cego de dogmas religiosos prescritos pela tradição.', selectionPercentage: 5 },
      { letter: 'E', text: 'A renúncia completa à vida cívica e à participação política na pólis.', selectionPercentage: 4 },
    ],
    correctOption: 'B',
    explanation: 'Para Aristóteles, a virtude é o ponto de equilíbrio entre a carência (falta) e o excesso. Por exemplo, a coragem é a justa medida entre a covardia (falta de audácia) e a temeridade (excesso irresponsável de audácia).',
    area: 'CIENCIAS_HUMANAS',
    discipline: 'Filosofia',
    topic: 'Ética Clássica',
    subtopic: 'Aristóteles e Justo Meio',
    year: 2024,
    difficulty: 'MEDIO',
    source: 'ENEM 2024',
    tags: ['Filosofia', 'Ética', 'Aristóteles'],
    totalAnswers: 330,
    correctAnswersCount: 254,
  },
  {
    id: 'q-hum-04',
    statement: 'O sociólogo Zygmunt Bauman cunhou o termo "Modernidade Líquida" para caracterizar a sociedade contemporânea. De acordo com a análise de Bauman, as relações sociais, de trabalho e afetivas na contemporaneidade distinguem-se por:',
    options: [
      { letter: 'A', text: 'Fragilidade dos vínculos, efemeridade, desregulamentação e constante incerteza.', selectionPercentage: 81 },
      { letter: 'B', text: 'Fortalecimento duradouro dos laços comunitários e estabilidade empregatícia perpétua.', selectionPercentage: 6 },
      { letter: 'C', text: 'Prevalência do pensamento coletivo sobre o individualismo consumista.', selectionPercentage: 5 },
      { letter: 'D', text: 'Solidariedade mecânica com pouca divisão social do trabalho.', selectionPercentage: 4 },
      { letter: 'E', text: 'Perenidade das instituições estatais protetoras dos indivíduos.', selectionPercentage: 4 },
    ],
    correctOption: 'A',
    explanation: 'A modernidade líquida de Bauman descreve um tempo de desconstrução de estruturas sólidas (família, carreira estável, comunidade), dando lugar a conexões voláteis, consumo acelerado, individualismo e sensação generalizada de insegurança e transitoriedade.',
    area: 'CIENCIAS_HUMANAS',
    discipline: 'Sociologia',
    topic: 'Sociologia Contemporânea',
    subtopic: 'Zygmunt Bauman',
    year: 2023,
    difficulty: 'FACIL',
    source: 'ENEM 2023',
    tags: ['Sociologia', 'Contemporaneidade', 'Bauman'],
    totalAnswers: 350,
    correctAnswersCount: 283,
  },

  // LINGUAGENS E CÓDIGOS
  {
    id: 'q-lin-01',
    statement: 'No romance "Memórias Póstumas de Brás Cubas" (1881), Machado de Assis inaugura o Realismo brasileiro rompendo frontalmente com as convenções românticas da época. A postura do narrador-defunto Brás Cubas expressa uma inovação literária caracterizada principalmente pela:',
    supportText: '"Não tive filhos, não transmiti a nenhuma criatura o legado da nossa miséria." (ASSIS, Machado de. Memórias Póstumas de Brás Cubas).',
    options: [
      { letter: 'A', text: 'Idealização heroica dos personagens e exaltação ufanista da pátria.', selectionPercentage: 5 },
      { letter: 'B', text: 'Ironia cáustica, desmistificação da burguesia e narrativa em primeira pessoa descompromissada com a moralidade vigente.', selectionPercentage: 83 },
      { letter: 'C', text: 'Linguagem carregada de sentimentalismo exacerbado e final redentor.', selectionPercentage: 4 },
      { letter: 'D', text: 'Valorização de lendas indígenas como símbolo de identidade nacional pura.', selectionPercentage: 4 },
      { letter: 'E', text: 'Foco exclusivo na descrição determinista e patológica das classes proletárias.', selectionPercentage: 4 },
    ],
    correctOption: 'B',
    explanation: 'Brás Cubas escreve da sepultura, o que lhe confere total liberdade para desmascarar a hipocrisia e a vaidade da elite oitocentista por meio da ironia, do pessimismo e da metalinguagem, traço central da estética realista machadiana.',
    area: 'LINGUAGENS',
    discipline: 'Literatura',
    topic: 'Realismo Brasileiro',
    subtopic: 'Machado de Assis',
    year: 2024,
    difficulty: 'MEDIO',
    source: 'ENEM 2024',
    tags: ['Literatura', 'Realismo', 'Machado de Assis'],
    totalAnswers: 340,
    correctAnswersCount: 282,
  },
  {
    id: 'q-lin-02',
    statement: 'Leia o trecho publicitário: "Não deixe a dengue se criar na sua casa. Eliminar a água parada é a única vacina que protege toda a vizinhança. Faça a sua parte!". Pela teoria da comunicação de Roman Jakobson, a função de linguagem predominante nesse texto é a:',
    options: [
      { letter: 'A', text: 'Função Emotiva (ou Expressiva), centrada nas emoções do emissor.', selectionPercentage: 6 },
      { letter: 'B', text: 'Função Conativa (ou Apelativa), voltada a persuadir o receptor e orientar seu comportamento.', selectionPercentage: 82 },
      { letter: 'C', text: 'Função Metalinguística, que utiliza o código para explicar a própria linguagem.', selectionPercentage: 5 },
      { letter: 'D', text: 'Função Fática, que busca apenas testar e manter o canal de comunicação aberto.', selectionPercentage: 4 },
      { letter: 'E', text: 'Função Poética, cuja ênfase repousa na elaboração rítmica e estética da mensagem.', selectionPercentage: 3 },
    ],
    correctOption: 'B',
    explanation: 'A função conativa/apelativa foca no receptor (destinatário), empregando verbos no modo imperativo ("Não deixe", "Eliminar", "Faça sua parte") e vocabulário persuasivo para influenciar diretamente as ações e atitudes do leitor.',
    area: 'LINGUAGENS',
    discipline: 'Português',
    topic: 'Funções da Linguagem',
    subtopic: 'Função Conativa',
    year: 2023,
    difficulty: 'FACIL',
    source: 'ENEM 2023',
    tags: ['Comunicação', 'Funções da Linguagem', 'Publicidade'],
    totalAnswers: 375,
    correctAnswersCount: 307,
  },
  {
    id: 'q-lin-03',
    statement: 'A variação linguística é um fenômeno natural em todas as línguas humanas. Considere o poema modernista "Pronominais", de Oswald de Andrade: "Dê-me um cigarro / Diz a gramática / Do professor e do aluno / E do mulato sabido / Mas o bom negro e o bom branco / Da Nação Brasileira / Dizem todos os dias / Deixa disso camarada / Me dá um cigarro." O poema de Oswald de Andrade propõe:',
    options: [
      { letter: 'A', text: 'A punição formal do uso de próclise em início de frase no cotidiano.', selectionPercentage: 5 },
      { letter: 'B', text: 'A valorização da norma culta europeia como padrão civilizatório nacional.', selectionPercentage: 4 },
      { letter: 'C', text: 'A legitimação da fala coloquial brasileira contra o purismo linguístico lusitano.', selectionPercentage: 85 },
      { letter: 'D', text: 'A substituição do ensino da gramática nas escolas por dialetos arcaicos.', selectionPercentage: 3 },
      { letter: 'E', text: 'A comprovação de que a língua portuguesa falada no Brasil é gramaticalmente deficiente.', selectionPercentage: 3 },
    ],
    correctOption: 'C',
    explanation: 'Oswald de Andrade, um dos líderes da Semana de Arte Moderna de 1922, defende a "língua brasileira" autêntica, viva no cotidiano popular ("Me dá um cigarro"), contra o rigor artificial da norma culta importada de Portugal ("Dê-me um cigarro").',
    area: 'LINGUAGENS',
    discipline: 'Literatura',
    topic: 'Modernismo Brasileiro',
    subtopic: 'Semana de 22 e Variação Linguística',
    year: 2024,
    difficulty: 'MEDIO',
    source: 'ENEM 2024',
    tags: ['Modernismo', 'Variação Linguística', 'Oswald de Andrade'],
    totalAnswers: 310,
    correctAnswersCount: 263,
  },
  {
    id: 'q-lin-04',
    statement: 'In the sentence: "Despite widespread efforts to mitigate climate change, greenhouse gas emissions continued to rise in 2025, according to recent global reports." The connector "Despite" introduces an idea of:',
    options: [
      { letter: 'A', text: 'Concession / Contrast (oposição entre esforços e continuidade do aumento).', selectionPercentage: 86 },
      { letter: 'B', text: 'Consequence / Result (resultado direto das medidas adotadas).', selectionPercentage: 5 },
      { letter: 'C', text: 'Temporal sequence (ordenação cronológica de eventos).', selectionPercentage: 4 },
      { letter: 'D', text: 'Condition (requisito obrigatório para o relatório).', selectionPercentage: 3 },
      { letter: 'E', text: 'Purpose (finalidade primordial da pesquisa ambiental).', selectionPercentage: 2 },
    ],
    correctOption: 'A',
    explanation: '"Despite" (apesar de / a despeito de) é uma preposição concessiva que expressa contraste ou concessão: embora tenham ocorrido amplos esforços, as emissões continuaram a subir.',
    area: 'LINGUAGENS',
    discipline: 'Inglês',
    topic: 'Língua Estrangeira',
    subtopic: 'Conectivos e Coesão',
    year: 2024,
    difficulty: 'FACIL',
    source: 'ENEM 2024',
    tags: ['Inglês', 'Conectivos', 'Interpretação'],
    totalAnswers: 320,
    correctAnswersCount: 275,
  },
];

export const SEED_SIMULADOS: Simulado[] = [
  {
    id: 'sim-01',
    title: 'Simulado Diagnóstico Geral ENEM 2026',
    description: 'Prova oficial de sondagem com questões selecionadas das 4 áreas do conhecimento para calibrar seu plano de estudos individual.',
    year: 2026,
    type: 'ENEM_COMPLETO',
    totalQuestions: 12,
    timeLimitMinutes: 45,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS', 'CIENCIAS_DA_NATUREZA', 'MATEMATICA'],
    questionIds: [
      'q-mat-01', 'q-mat-02', 'q-mat-03', 'q-mat-04',
      'q-nat-01', 'q-nat-02', 'q-nat-03', 'q-nat-04',
      'q-hum-01', 'q-hum-02', 'q-hum-03', 'q-hum-04',
      'q-lin-01', 'q-lin-02', 'q-lin-03', 'q-lin-04',
    ],
    published: true,
    createdAt: '2026-02-01T08:00:00.000Z',
  },
  {
    id: 'sim-02',
    title: 'Simulado Expresso Humanas & Linguagens',
    description: 'Foco intensivo na interpretação textual, história social, filosofia e literatura para o 1º dia do ENEM.',
    year: 2026,
    type: 'POR_AREA',
    totalQuestions: 8,
    timeLimitMinutes: 30,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'q-hum-01', 'q-hum-02', 'q-hum-03', 'q-hum-04',
      'q-lin-01', 'q-lin-02', 'q-lin-03', 'q-lin-04',
    ],
    published: true,
    createdAt: '2026-02-15T14:00:00.000Z',
  },
];

export const SEED_ESSAY_TOPICS: EssayTopic[] = [
  {
    id: 'tema-01',
    title: 'Saúde Mental dos Jovens e Redes Sociais',
    theme: 'Desafios para a valorização e preservação da saúde mental da juventude na era digital brasileira',
    year: 2026,
    difficulty: 'MEDIO',
    instructions: 'A partir da leitura dos textos motivadores e com base nos conhecimentos construídos ao longo de sua formação, redija um texto dissertativo-argumentativo em modalidade escrita formal da língua portuguesa sobre o tema, apresentando proposta de intervenção que respeite os direitos humanos. Selecione, organize e relacione, de forma coerente e coesa, argumentos e fatos para defesa de seu ponto de vista.',
    motivatingTexts: [
      {
        id: 1,
        title: 'Texto I - O Impacto das Telas',
        content: 'Estudos conduzidos pela Organização Mundial da Saúde (OMS) apontam que mais de 30% dos adolescentes brasileiros relatam sintomas frequentes de ansiedade, insônia e baixa autoestima associados ao uso compulsivo de redes sociais. A comparação social contínua promovida por algoritmos de engajamento intensifica quadros depressivos e FOMO (Fear of Missing Out).',
        source: 'Relatório OMS / UNICEF Brasil (2024)',
      },
      {
        id: 2,
        title: 'Texto II - Legislação e Escolas',
        content: 'O Estatuto da Criança e do Adolescente (ECA) estabelece a proteção integral à saúde mental de crianças e adolescentes. Contudo, menos de 20% das escolas públicas contam com equipes multidisciplinares com psicólogos e assistentes sociais para acolhimento preventivo de sofrimento emocional.',
        source: 'Conselho Federal de Psicologia (CFP)',
      },
      {
        id: 3,
        title: 'Texto III - Dependência Tecnológica',
        content: 'O tempo médio de conexão diária do jovem brasileiro em telas móveis superou 7 horas por dia, liderando rankings mundiais. Especialistas alertam que a hiperconectividade sem educação midiática e sem apoio socioafetivo converte as plataformas virtuais em ambientes de isolamento presencial.',
        source: 'Centro de Estudos para o Desenvolvimento da Sociedade da Informação (Cetic.br)',
      },
    ],
    createdAt: '2026-01-20T10:00:00.000Z',
  },
  {
    id: 'tema-02',
    title: 'Evasão Escolar no Ensino Médio',
    theme: 'Caminhos para combater a evasão escolar e garantir a permanência de jovens no Ensino Médio',
    year: 2025,
    difficulty: 'MEDIO',
    instructions: 'Redija um texto dissertativo-argumentativo em norma padrão sobre a evasão escolar na juventude, articulando causas socioeconômicas e soluções efetivas.',
    motivatingTexts: [
      {
        id: 1,
        title: 'Texto I - Dados da Evasão',
        content: 'Cerca de 500 mil jovens abandonam anualmente a escola no Brasil antes de concluir o Ensino Médio. A necessidade de ingresso precoce no mercado informal de trabalho para complementar a renda familiar figura como o principal motivo alegado pelos estudantes.',
        source: 'Censo Escolar / INEP',
      },
      {
        id: 2,
        title: 'Texto II - O Programa Pé-de-Meia',
        content: 'A implementação de incentivos financeiros governamentais atrelados à frequência escolar e à conclusão das etapas do Ensino Médio busca criar um colchão protetivo, reduzindo o custo de oportunidade do jovem permanecer estudando.',
        source: 'Ministério da Educação (MEC)',
      },
    ],
    createdAt: '2026-02-01T12:00:00.000Z',
  },
  {
    id: 'tema-03',
    title: 'Inteligência Artificial e o Futuro do Trabalho',
    theme: 'Impactos e dilemas éticos da automação e da Inteligência Artificial no mercado de trabalho brasileiro',
    year: 2026,
    difficulty: 'DIFICIL',
    instructions: 'Discuta criticamente como o avanço veloz da Inteligência Artificial afeta profissões e trabalhadores no Brasil, propondo medidas inclusivas de requalificação profissional.',
    motivatingTexts: [
      {
        id: 1,
        title: 'Texto I - A Transformação Produtiva',
        content: 'A automação cognitiva impulsionada por modelos generativos de IA não atinge apenas postos operacionais, mas também funções intelectuais e de escritório. Estima-se que 40% dos postos de trabalho no Brasil sofrerão algum grau de reestruturação até 2030.',
        source: 'Fórum Econômico Mundial (WEF)',
      },
    ],
    createdAt: '2026-02-10T16:00:00.000Z',
  },
];

