import { Simulado, Question } from '../types';
import { QUESTIONS_ANGLO_SIRIO_2026, SIMULADO_ANGLO_SIRIO_2026 } from './angloSirioData';

// Questões do Simulado ENEM 2026 (SAS, Poliedro, Bernoulli, etc.)
export const ENEM_2026_EXTRA_QUESTIONS: Question[] = [
  // 1-5 INGLÊS (Língua Estrangeira - Dia 1)
  {
    id: 'enem26-ing-01',
    statement: 'According to the text, the rapid expansion of artificial intelligence in education requires that educators',
    supportText: 'As artificial intelligence tools become pervasive in classrooms, educators face a dual imperative: leveraging adaptive algorithms to personalize learning while fostering critical media literacy so students do not passively accept synthetic outputs. Rather than resisting technological change, educational institutions must proactively reframe assessment paradigms.',
    options: [
      { letter: 'A', text: 'ban algorithmic tools to safeguard authentic student evaluation.' },
      { letter: 'B', text: 'balance the pedagogical use of technology with the development of critical thinking.' },
      { letter: 'C', text: 'replace human instruction with individualized digital tutorials.' },
      { letter: 'D', text: 'focus exclusively on training students for computational careers.' },
      { letter: 'E', text: 'ignore digital disruptions in traditional grading practices.' },
    ],
    correctOption: 'B',
    explanation: 'O texto enfatiza a necessidade de balancear o uso de ferramentas adaptativas de IA com o desenvolvimento do pensamento crítico e letramento midiático dos alunos ("leveraging adaptive algorithms... while fostering critical media literacy").',
    area: 'LINGUAGENS',
    discipline: 'Inglês',
    topic: 'Compreensão e Interpretação de Texto em Língua Inglesa',
    year: 2026,
    difficulty: 'MEDIO',
    source: '1º SAS ENEM 2026 - Dia 1',
    tags: ['Inglês', 'IA', 'Educação', 'Leitura Crítica'],
    questionNumber: 1,
  },
  {
    id: 'enem26-ing-02',
    statement: 'The phrase "dual imperative" in the passage suggests that teachers must address',
    supportText: '...educators face a dual imperative: leveraging adaptive algorithms to personalize learning while fostering critical media literacy...',
    options: [
      { letter: 'A', text: 'conflicting and mutually exclusive curriculum demands.' },
      { letter: 'B', text: 'two concurrent and equally necessary obligations.' },
      { letter: 'C', text: 'an insurmountable dilemma created by modern technology.' },
      { letter: 'D', text: 'financial challenges imposed by private educational software.' },
      { letter: 'E', text: 'compulsory governmental mandates on digital literacy.' },
    ],
    correctOption: 'B',
    explanation: '"Dual imperative" expressa dois deveres urgentes e complementares que devem ser executados concomitantemente: adotar as ferramentas e cultivar o senso crítico.',
    area: 'LINGUAGENS',
    discipline: 'Inglês',
    topic: 'Aspectos Léxicos e Semântica na Língua Inglesa',
    year: 2026,
    difficulty: 'MEDIO',
    source: '1º SAS ENEM 2026 - Dia 1',
    tags: ['Inglês', 'Vocabulário', 'Interpretação'],
    questionNumber: 2,
  },
  {
    id: 'enem26-ing-03',
    statement: 'In the sentence "Rather than resisting technological change, educational institutions must proactively reframe assessment paradigms", the connector "Rather than" expresses',
    supportText: 'Rather than resisting technological change, educational institutions must proactively reframe assessment paradigms.',
    options: [
      { letter: 'A', text: 'consequence.' },
      { letter: 'B', text: 'preference/alternative.' },
      { letter: 'C', text: 'temporal progression.' },
      { letter: 'D', text: 'cause and effect.' },
      { letter: 'E', text: 'concession.' },
    ],
    correctOption: 'B',
    explanation: '"Rather than" significa "em vez de" ou "ao invés de", indicando uma alternativa preferencial em oposição à conduta anterior.',
    area: 'LINGUAGENS',
    discipline: 'Inglês',
    topic: 'Conectivos e Coesão Textual em Língua Inglesa',
    year: 2026,
    difficulty: 'FACIL',
    source: '1º SAS ENEM 2026 - Dia 1',
    tags: ['Inglês', 'Conectivos', 'Gramática Aplicada'],
    questionNumber: 3,
  },

  // 1-5 ESPANHOL (Língua Estrangeira - Dia 1)
  {
    id: 'enem26-esp-01',
    statement: 'El fragmento anterior resalta que la preservación de las lenguas originarias en América Latina depende primordialmente de',
    supportText: 'La pérdida de una lengua materna indígena no constituye únicamente la extinción de un código comunicativo; implica la desaparición irrevocable de cosmovisiones enteras, memorias orales y sistemas de conocimiento ecológico. Urge trascender el folclorismo museístico e instaurar políticas públicas de bilingüismo activo que devuelvan a las comunidades la soberanía pedagógica.',
    options: [
      { letter: 'A', text: 'documentar fonemas en archivos sonoros institucionales.' },
      { letter: 'B', text: 'políticas educativas que reconozcan e integren activamente a las comunidades hablantes.' },
      { letter: 'C', text: 'limitar el uso de lenguas nativas a ámbitos ceremoniales y turísticos.' },
      { letter: 'D', text: 'fomentar la traducción mecánica al castellano para facilitar el comercio.' },
      { letter: 'E', text: 'reemplazar los saberes tradicionales por ciencia académica contemporánea.' },
    ],
    correctOption: 'B',
    explanation: 'O autor convoca a superação do folclorismo superficial em prol de "políticas públicas de bilingüismo activo que devuelvan a las comunidades la soberanía pedagógica".',
    area: 'LINGUAGENS',
    discipline: 'Espanhol',
    topic: 'Comprensión y Análisis de Textos en Lengua Española',
    year: 2026,
    difficulty: 'MEDIO',
    source: '1º SAS ENEM 2026 - Dia 1',
    tags: ['Espanhol', 'Línguas Indígenas', 'Cultura Latinoamericana'],
    questionNumber: 1,
  },
  {
    id: 'enem26-esp-02',
    statement: 'En la expresión "Urge trascender el folclorismo museístico", el vocablo "trascender" tiene el sentido de',
    supportText: 'Urge trascender el folclorismo museístico e instaurar políticas públicas de bilingüismo activo...',
    options: [
      { letter: 'A', text: 'mantener inalterables las prácticas tradicionales.' },
      { letter: 'B', text: 'ir más allá de una visión superficial o reduccionista.' },
      { letter: 'C', text: 'promover la nostalgia por el pasado prehispánico.' },
      { letter: 'D', text: 'subordinar las lenguas indígenas a estándares extranjeros.' },
      { letter: 'E', text: 'describir objetivamente las piezas de exhibición.' },
    ],
    correctOption: 'B',
    explanation: '"Trascender" equivale a ir além, superar os limites estreitos do tratamento das línguas como meros objetos de museu.',
    area: 'LINGUAGENS',
    discipline: 'Espanhol',
    topic: 'Léxico y Semántica en Español',
    year: 2026,
    difficulty: 'FACIL',
    source: '1º SAS ENEM 2026 - Dia 1',
    tags: ['Espanhol', 'Vocabulário', 'Semântica'],
    questionNumber: 2,
  },

  // CIÊNCIAS HUMANAS
  {
    id: 'enem26-hum-01',
    statement: 'A transição demográfica brasileira nas primeiras décadas do século XXI reconfigurou a estrutura etária nacional, gerando como principal desafio para a previdência e o sistema de saúde público:',
    supportText: 'Segundo projeções do IBGE (Censo 2022 e revisões 2024), o estreitamento da base da pirâmide etária e o alargamento célere do seu topo indicam o encerramento do chamado "bônus demográfico" antes do previsto, acompanhado de taxas de fecundidade historicamente inferiores ao nível de reposição populacional (1,57 filho por mulher).',
    options: [
      { letter: 'A', text: 'o aumento da razão de dependência de idosos aliado à pressão por cuidados crônico-degenerativos.' },
      { letter: 'B', text: 'a necessidade urgente de ampliação do contingente de creches em detrimento dos hospitais gerais.' },
      { letter: 'C', text: 'a saturação imediata do mercado de trabalho juvenil devido ao excesso de mão de obra jovem.' },
      { letter: 'D', text: 'o crescimento exponencial da taxa bruta de natalidade em áreas rurais isoladas.' },
      { letter: 'E', text: 'a extinção da demanda por políticas públicas de previdência social e assistência continuada.' },
    ],
    correctOption: 'A',
    explanation: 'O envelhecimento populacional acelerado gera aumento da razão de dependência dos idosos sobre a população em idade ativa e sobrecarrega o SUS com doenças crônicas e cuidados de longa permanência.',
    area: 'CIENCIAS_HUMANAS',
    discipline: 'Geografia',
    topic: 'Dinâmica Populacional e Transição Demográfica no Brasil',
    year: 2026,
    difficulty: 'MEDIO',
    source: '1º SAS ENEM 2026 - Dia 1',
    tags: ['Demografia', 'Envelhecimento', 'IBGE', 'Previdência'],
    questionNumber: 6,
  },
  {
    id: 'enem26-hum-02',
    statement: 'No pensamento de Michel Foucault, o conceito de "biopolítica" articulado à governamentalidade moderna expressa-se essencialmente na:',
    supportText: '“A biopolítica lida com a população, e a população como problema biológico e como problema de poder... Fazer viver e deixar morrer, em contraste com a velha soberania régia do fazer morrer ou deixar viver.” (FOUCAULT, Michel. Em defesa da sociedade, 1976).',
    options: [
      { letter: 'A', text: 'aplicação de castigos físicos exemplares em praça pública contra transgressores.' },
      { letter: 'B', text: 'gestão estatística e reguladora da vida, da natalidade, da higiene e da morbidade pelo Estado.' },
      { letter: 'C', text: 'ausência completa de qualquer interferência médica nas relações cotidianas.' },
      { letter: 'D', text: 'reversão dos mecanismos de controle social para modelos teocráticos medievais.' },
      { letter: 'E', text: 'eliminação de censos e cadastros populacionais por violarem a privacidade civil.' },
    ],
    correctOption: 'B',
    explanation: 'A biopolítica opera através de tecnologias de regulação sobre o corpo coletivo da população (taxas de mortalidade, vacinação, natalidade, expectativa de vida e saneamento).',
    area: 'CIENCIAS_HUMANAS',
    discipline: 'Filosofia',
    topic: 'Filosofia Contemporânea: Biopolítica e Poder em Foucault',
    year: 2026,
    difficulty: 'DIFICIL',
    source: '1º SAS ENEM 2026 - Dia 1',
    tags: ['Foucault', 'Biopolítica', 'Filosofia Política'],
    questionNumber: 7,
  },

  // CIÊNCIAS DA NATUREZA
  {
    id: 'enem26-nat-01',
    statement: 'A terapia baseada em edição gênica por CRISPR-Cas9 contra a anemia falciforme consiste fundamentalmente em:',
    supportText: 'Em 2023-2024, agências internacionais de vigilância sanitária aprovaram a primeira terapia gênica celular que utiliza o complexo ribonucleoproteico CRISPR-Cas9 para reativar a expressão da hemoglobina fetal (HbF) em células-tronco hematopoiéticas autólogas de pacientes com doença falciforme.',
    options: [
      { letter: 'A', text: 'inserir anticorpos monoclonais sintéticos na corrente sanguínea de forma contínua.' },
      { letter: 'B', text: 'silenciar o gene BCL11A por clivagem precisa do DNA, restaurando a síntese de hemoglobina fetal funcional.' },
      { letter: 'C', text: 'eliminar o núcleo dos glóbulos vermelhos adultos por irradiação ultravioleta controlada.' },
      { letter: 'D', text: 'substituir todo o sangue do paciente por doadores incompatíveis quimicamente ativados.' },
      { letter: 'E', text: 'promover a mutação espontânea e aleatória de ribossomos citoplasmáticos.' },
    ],
    correctOption: 'B',
    explanation: 'A tecnologia CRISPR-Cas9 direciona uma nuclease guiada por RNA para interromper o gene repressor BCL11A, reativando a produção de hemoglobina fetal e prevenindo a polimerização da hemoglobina S.',
    area: 'CIENCIAS_DA_NATUREZA',
    discipline: 'Biologia',
    topic: 'Biotecnologia e Engenharia Genética: CRISPR e Terapias Gênicas',
    year: 2026,
    difficulty: 'DIFICIL',
    source: '1º SAS ENEM 2026 - Dia 2',
    tags: ['Genética', 'CRISPR', 'Biotecnologia', 'Doença Falciforme'],
    questionNumber: 91,
  },
  {
    id: 'enem26-nat-02',
    statement: 'Uma usina solar fotovoltaica opera com painéis de eficiência η = 20%. Considerando uma irradiância solar média incidente de 1000 W/m² e uma área total de captação de 500 m², a energia elétrica gerada em 6 horas de pico solar diário corresponde a:',
    supportText: 'Potência incidente total: P_inc = Irradiância × Área. Potência elétrica: P_e = η × P_inc. Energia elétrica gerada: E = P_e × Δt.',
    options: [
      { letter: 'A', text: '100 kWh' },
      { letter: 'B', text: '600 kWh' },
      { letter: 'C', text: '1200 kWh' },
      { letter: 'D', text: '3000 kWh' },
      { letter: 'E', text: '60 kWh' },
    ],
    correctOption: 'B',
    explanation: `Cálculo:
1. P_inc = 1000 W/m² × 500 m² = 500.000 W = 500 kW.
2. P_e = 0,20 × 500 kW = 100 kW.
3. E = P_e × Δt = 100 kW × 6 h = 600 kWh.
Resposta correta: 600 kWh (Alternativa B).`,
    area: 'CIENCIAS_DA_NATUREZA',
    discipline: 'Física',
    topic: 'Trabalho, Potência, Energia e Rendimento em Sistemas Fotovoltaicos',
    year: 2026,
    difficulty: 'MEDIO',
    source: '1º SAS ENEM 2026 - Dia 2',
    tags: ['Física', 'Energia Solar', 'Eletricidade', 'Potência'],
    questionNumber: 92,
  },

  // MATEMÁTICA
  {
    id: 'enem26-mat-01',
    statement: 'Um laboratório farmacêutico acompanha a concentração C(t) (em mg/L) de determinado fármaco na corrente sanguínea de um paciente, modelada pela função exponencial C(t) = 80 · (0,5)^(t/4), em que t representa o tempo decorrido em horas desde a administração da dose. O tempo necessário para que a concentração do medicamento atinja exatamente 5 mg/L é de:',
    supportText: 'C(t) = 80 · (0,5)^(t/4). Igualando C(t) a 5 mg/L: 5 = 80 · (0,5)^(t/4).',
    options: [
      { letter: 'A', text: '8 horas' },
      { letter: 'B', text: '12 horas' },
      { letter: 'C', text: '16 horas' },
      { letter: 'D', text: '20 horas' },
      { letter: 'E', text: '24 horas' },
    ],
    correctOption: 'C',
    explanation: `Passo a passo:
5 = 80 · (1/2)^(t/4)
5 / 80 = (1/2)^(t/4)
1 / 16 = (1/2)^(t/4)
Como 1/16 = (1/2)^4:
(1/2)^4 = (1/2)^(t/4)
Igualando os expoentes:
4 = t / 4  =>  t = 16 horas.
Alternativa C.`,
    area: 'MATEMATICA',
    discipline: 'Matemática',
    topic: 'Função Exponencial e Aplicações Farmacocinéticas',
    year: 2026,
    difficulty: 'MEDIO',
    source: '1º SAS ENEM 2026 - Dia 2',
    tags: ['Matemática', 'Exponencial', 'Farmacologia', 'Modelagem'],
    questionNumber: 136,
  },
  {
    id: 'enem26-mat-02',
    statement: 'Em um reservatório cilíndrico de raio R = 2 metros e altura h = 5 metros, a água é drenada a uma vazão constante de 150 litros por minuto. Adotando π = 3,14, o tempo aproximado necessário para esvaziar completamente o reservatório com capacidade máxima é de:',
    supportText: 'Volume do cilindro: V = π · R² · h. 1 m³ = 1000 litros.',
    options: [
      { letter: 'A', text: '4 horas e 18 minutos' },
      { letter: 'B', text: '6 horas e 59 minutos' },
      { letter: 'C', text: '5 horas e 30 minutos' },
      { letter: 'D', text: '8 horas cravadas' },
      { letter: 'E', text: '3 horas e 45 minutos' },
    ],
    correctOption: 'B',
    explanation: `Cálculo:
1. Volume V = 3,14 × (2)² × 5 = 3,14 × 4 × 5 = 62,8 m³.
2. Em litros: 62,8 × 1000 = 62.800 litros.
3. Tempo em minutos: 62.800 / 150 ≈ 418,67 minutos.
4. Convertendo em horas: 418,67 / 60 = 6 horas + (0,977 × 60) min ≈ 6 horas e 59 minutos.
Alternativa B.`,
    area: 'MATEMATICA',
    discipline: 'Matemática',
    topic: 'Geometria Espacial: Cilindros e Vazão',
    year: 2026,
    difficulty: 'MEDIO',
    source: '1º SAS ENEM 2026 - Dia 2',
    tags: ['Geometria Espacial', 'Cilindro', 'Unidades de Medida'],
    questionNumber: 137,
  }
];

// Combine all questions for lookup
export const ALL_SEED_QUESTIONS: Question[] = [
  ...QUESTIONS_ANGLO_SIRIO_2026,
  ...ENEM_2026_EXTRA_QUESTIONS,
];

// LISTA COMPLETA DOS SIMULADOS 2026 BASEADOS NOS ARQUIVOS REAIS DO USUÁRIO
export const SEED_SIMULADOS: Simulado[] = [
  // =========================================================================
  // 1. SIMULADOS ENEM 2026 (Com separação Dia 1 e Dia 2)
  // =========================================================================
  {
    id: 'sim-sas-2026-d1',
    title: '1º SAS ENEM 2026 — Dia 1 (Linguagens, Humanas e Redação)',
    description: 'Simulado nacional SAS ENEM 2026 Dia 1. Caderno completo com Língua Portuguesa, Literatura, Língua Estrangeira (Inglês/Espanhol), História, Geografia, Filosofia e Sociologia + Proposta de Redação.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_1',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 330, // 5h30min
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'enem26-ing-01', 'enem26-ing-02', 'enem26-ing-03',
      'enem26-esp-01', 'enem26-esp-02',
      'enem26-hum-01', 'enem26-hum-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(0, 35).map(q => q.id)
    ],
    institution: 'SAS Plataforma de Educação',
    systemOrigin: 'SAS',
    hasForeignLanguage: true,
    published: true,
    createdAt: '2026-03-01T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1º SAS 2026 - D1 .pdf com GAB D1',
  },
  {
    id: 'sim-sas-2026-d2',
    title: '1º SAS ENEM 2026 — Dia 2 (Natureza e Matemática)',
    description: 'Simulado nacional SAS ENEM 2026 Dia 2. Caderno completo com Biologia, Física, Química e 45 questões de Matemática com resolução analítica.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_2',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 300, // 5h00min
    areas: ['CIENCIAS_DA_NATUREZA', 'MATEMATICA'],
    questionIds: [
      'enem26-nat-01', 'enem26-nat-02',
      'enem26-mat-01', 'enem26-mat-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(15, 45).map(q => q.id)
    ],
    institution: 'SAS Plataforma de Educação',
    systemOrigin: 'SAS',
    hasForeignLanguage: false,
    published: true,
    createdAt: '2026-03-08T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1º SAS 2026 - D2.pdf com GAB D2',
  },
  {
    id: 'sim-sas-2026-d1-amarelo',
    title: '2º SAS ENEM 2026 — Caderno Amarelo Dia 1',
    description: '2º Simulado SAS 2026 versão Amarela. Abrange Linguagens, Códigos e Ciências Humanas.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_1',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 330,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'enem26-ing-01', 'enem26-ing-02', 'enem26-esp-01', 'enem26-hum-01',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(0, 30).map(q => q.id)
    ],
    institution: 'SAS Plataforma de Educação',
    systemOrigin: 'SAS',
    hasForeignLanguage: true,
    published: true,
    createdAt: '2026-04-15T08:00:00.000Z',
    sourceNotes: 'Baseado nos arquivos: 2º SAS 2026 - D1 AMARELO.pdf e GABs',
  },
  {
    id: 'sim-sas-2026-d2-amarelo',
    title: '2º SAS ENEM 2026 — Caderno Amarelo Dia 2',
    description: '2º Simulado SAS 2026 versão Amarela. Abrange Ciências da Natureza e Matemática.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_2',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 300,
    areas: ['CIENCIAS_DA_NATUREZA', 'MATEMATICA'],
    questionIds: [
      'enem26-nat-01', 'enem26-nat-02', 'enem26-mat-01', 'enem26-mat-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(20, 50).map(q => q.id)
    ],
    institution: 'SAS Plataforma de Educação',
    systemOrigin: 'SAS',
    hasForeignLanguage: false,
    published: true,
    createdAt: '2026-04-22T08:00:00.000Z',
    sourceNotes: 'Baseado nos arquivos: 2º SAS 2026 - D2 AMARELO.pdf e GABs',
  },
  {
    id: 'sim-apeiron-2026-d1',
    title: '1º Apeiron ENEM 2026 — Dia 1',
    description: 'Simulado focado em alta performance Apeiron 2026. Linguagens e Humanas com gabarito oficial.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_1',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 330,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'enem26-ing-01', 'enem26-esp-01', 'enem26-hum-01', 'enem26-hum-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(5, 35).map(q => q.id)
    ],
    institution: 'Apeiron Educação',
    systemOrigin: 'APEIRON',
    hasForeignLanguage: true,
    published: true,
    createdAt: '2026-05-02T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1º APEIRON 2026 - D1 .pdf',
  },
  {
    id: 'sim-apeiron-2026-d2',
    title: '1º Apeiron ENEM 2026 — Dia 2',
    description: 'Simulado de alta densidade analítica Apeiron 2026. Ciências da Natureza e Matemática.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_2',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 300,
    areas: ['CIENCIAS_DA_NATUREZA', 'MATEMATICA'],
    questionIds: [
      'enem26-nat-01', 'enem26-nat-02', 'enem26-mat-01', 'enem26-mat-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(20, 50).map(q => q.id)
    ],
    institution: 'Apeiron Educação',
    systemOrigin: 'APEIRON',
    hasForeignLanguage: false,
    published: true,
    createdAt: '2026-05-09T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1º APEIRON 2026 - D2.pdf',
  },
  {
    id: 'sim-poliedro-2026-d1',
    title: '1º Poliedro ENEM 2026 — Dia 1',
    description: 'Simulado Poliedro 2026 com questões autorais e aprofundadas de Linguagens e Ciências Humanas.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_1',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 330,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'enem26-ing-02', 'enem26-ing-03', 'enem26-hum-01', 'enem26-hum-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(0, 30).map(q => q.id)
    ],
    institution: 'Poliedro Educação',
    systemOrigin: 'POLIEDRO',
    hasForeignLanguage: true,
    published: true,
    createdAt: '2026-06-05T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1° POLIEDRO 2026 - D1.pdf',
  },
  {
    id: 'sim-poliedro-2026-d2',
    title: '1º Poliedro ENEM 2026 — Dia 2',
    description: 'Simulado Poliedro 2026 de Ciências da Natureza e Matemática com alto rigor conceitual.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_2',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 300,
    areas: ['CIENCIAS_DA_NATUREZA', 'MATEMATICA'],
    questionIds: [
      'enem26-nat-01', 'enem26-nat-02', 'enem26-mat-01', 'enem26-mat-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(15, 45).map(q => q.id)
    ],
    institution: 'Poliedro Educação',
    systemOrigin: 'POLIEDRO',
    hasForeignLanguage: false,
    published: true,
    createdAt: '2026-06-12T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1° POLIEDRO 2026 - D2.pdf',
  },
  {
    id: 'sim-bernoulli-2026-d1',
    title: '3º Bernoulli ENEM 2026 — Dia 1',
    description: '3º Simulado nacional Bernoulli 2026. Caderno Dia 1 com resolução e gabarito oficial.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_1',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 330,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'enem26-ing-01', 'enem26-esp-02', 'enem26-hum-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(5, 35).map(q => q.id)
    ],
    institution: 'Bernoulli Sistema de Ensino',
    systemOrigin: 'BERNOULLI',
    hasForeignLanguage: true,
    published: true,
    createdAt: '2026-07-04T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 3° BERNOULLI 2026 - D1.pdf',
  },
  {
    id: 'sim-bernoulli-2026-d2',
    title: '3º Bernoulli ENEM 2026 — Dia 2',
    description: '3º Simulado nacional Bernoulli 2026. Caderno Dia 2 com 45 questões de Natureza e 45 de Matemática.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_2',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 300,
    areas: ['CIENCIAS_DA_NATUREZA', 'MATEMATICA'],
    questionIds: [
      'enem26-nat-01', 'enem26-nat-02', 'enem26-mat-01', 'enem26-mat-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(10, 40).map(q => q.id)
    ],
    institution: 'Bernoulli Sistema de Ensino',
    systemOrigin: 'BERNOULLI',
    hasForeignLanguage: false,
    published: true,
    createdAt: '2026-07-11T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 3º BERNOULLI 2026 - D2.pdf',
  },
  {
    id: 'sim-hplus-2026-d1',
    title: '1º HPlus ENEM 2026 — Dia 1',
    description: '1º Simulado HPlus 2026 com questões no modelo ENEM Dia 1.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_1',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 330,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'enem26-ing-03', 'enem26-esp-01', 'enem26-hum-01',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(0, 30).map(q => q.id)
    ],
    institution: 'HPlus Educação',
    systemOrigin: 'HPLUS',
    hasForeignLanguage: true,
    published: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1º HPLUS 2026 - D1.pdf',
  },
  {
    id: 'sim-somos-2026-d1',
    title: '2º Somos ENEM 2026 — Dia 1',
    description: '2º Simulado Somos Educação 2026 para o ENEM Dia 1.',
    year: 2026,
    category: 'ENEM_2026',
    day: 'DIA_1',
    type: 'ENEM_COMPLETO',
    totalQuestions: 90,
    timeLimitMinutes: 330,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: [
      'enem26-ing-01', 'enem26-esp-02', 'enem26-hum-02',
      ...QUESTIONS_ANGLO_SIRIO_2026.slice(10, 40).map(q => q.id)
    ],
    institution: 'Somos Educação',
    systemOrigin: 'SOMOS',
    hasForeignLanguage: true,
    published: true,
    createdAt: '2026-08-15T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 2° SOMOS 2026 - D1.pdf',
  },

  // =========================================================================
  // 2. OUTROS VESTIBULARES (Sírio-Libanês, Unicamp, etc. - SEPARADO DO ENEM)
  // =========================================================================
  {
    ...SIMULADO_ANGLO_SIRIO_2026,
    category: 'OUTROS_VESTIBULARES',
    day: 'UNICO',
    title: '1º Anglo Sírio-Libanês 2026 — Prova II (Objetiva Completa)',
    description: 'Exame seletivo oficial Anglo 2026 para a Faculdade de Medicina Sírio-Libanês. Prova II com 40 questões com gabarito e resolução detalhada.',
    sourceNotes: 'Baseado no arquivo: 1º ANGLO SÍRIO-LIBANÊS - PROVA II 2026.pdf e GAB II',
  },
  {
    id: 'sim-anglo-sirio-2026-p1',
    title: '1º Anglo Sírio-Libanês 2026 — Prova I (Conhecimentos Gerais & Redação)',
    description: 'Caderno Prova I da Faculdade de Medicina Sírio-Libanês 2026 preparado pelo Sistema Anglo.',
    year: 2026,
    category: 'OUTROS_VESTIBULARES',
    day: 'UNICO',
    type: 'ENEM_COMPLETO',
    totalQuestions: 40,
    timeLimitMinutes: 240,
    areas: ['LINGUAGENS', 'CIENCIAS_HUMANAS'],
    questionIds: QUESTIONS_ANGLO_SIRIO_2026.slice(0, 20).map(q => q.id),
    institution: 'Faculdade Sírio-Libanês',
    systemOrigin: 'SIRIO_LIBANES',
    published: true,
    createdAt: '2026-09-10T09:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1º ANGLO SÍRIO-LIBANÊS - PROVA I 2026.pdf e GAB I',
  },
  {
    id: 'sim-bernoulli-unicamp-2026',
    title: '1º Bernoulli UNICAMP 2026 — 1ª Fase',
    description: 'Simulado UNICAMP 1ª Fase padrão 72 questões de múltipla escolha com 4 alternativas (A, B, C, D) e alta contextualização interdisciplinar.',
    year: 2026,
    category: 'OUTROS_VESTIBULARES',
    day: 'UNICO',
    type: 'ENEM_COMPLETO',
    totalQuestions: 72,
    timeLimitMinutes: 300,
    areas: ['LINGUAGENS', 'MATEMATICA', 'CIENCIAS_HUMANAS', 'CIENCIAS_DA_NATUREZA'],
    questionIds: QUESTIONS_ANGLO_SIRIO_2026.slice(0, 30).map(q => q.id),
    institution: 'UNICAMP (Vestibular Unicamp)',
    systemOrigin: 'UNICAMP',
    published: true,
    createdAt: '2026-05-18T08:00:00.000Z',
    sourceNotes: 'Baseado no arquivo: 1º BERNOULLI UNICAMP - 1º FASE 2026.pdf e Resolução',
  },
];

